WayfireWM/wayfire

plugins/single_plugins/center-view.cpp, plugins/single_plugins/meson.build
A plugin to open all normal windows in the center of the screen instead of the top-left corner.
=> Center-view plugin

plugins/single_plugins/meson.build, plugins/single_plugins/place.cpp
Add a basic window placement plugin with three placement modes.
This plugin was based off of the center-view plugin by Adrian
Vovk. It contains the same code as center-view for the center
placement mode. The valid mode config keys are cascade, center
and random.
=> Add place plugin

plugins/animate/animate.cpp, plugins/decor/deco-subsurface.cpp, plugins/single_plugins/compositor-view-test.cpp, plugins/single_plugins/grid.cpp, plugins/single_plugins/meson.build, plugins/single_plugins/move.cpp, plugins/single_plugins/resize.cpp, plugins/single_plugins/snap_signal.hpp, plugins/single_plugins/switcher.cpp, plugins/wobbly/wobbly.cpp, src/api/compositor-surface.hpp, src/api/compositor-view.hpp, src/api/opengl.hpp, src/api/render-manager.hpp, src/api/view.hpp, src/core/core.cpp, src/core/seat/input-manager.cpp, src/core/seat/input-manager.hpp, src/core/seat/keyboard.cpp, src/meson.build, src/output/output.cpp, src/output/render-manager.cpp, src/view/compositor-view.cpp, src/view/priv-view.hpp, src/view/surface.cpp, src/view/view-util.cpp, src/view/view.cpp, src/view/xwayland.cpp
This PR implements a new type of view, compositor views. They have the same interface as regular views, however they come with compositor-generated content. Current use: move plugin. Using compositor views we can temporarily show a view on multiple monitors, so that the user sees a "smooth" transition between outputs. Once the move plugin exits, the view remains visible on only one output, as is designed.
The PR also uses compositor views to provide preview when snapping windows with the move plugin.
Fixes #99 Fixes #92 Fixes #12
=> Add compositor view support

plugins/animate/fire/fire.cpp, plugins/animate/fire/particle.cpp, plugins/animate/system_fade.hpp, plugins/cube/cube.cpp, plugins/decor/deco-subsurface.cpp, plugins/single_plugins/compositor-view-test.cpp, plugins/single_plugins/expo.cpp, plugins/single_plugins/fisheye.cpp, plugins/single_plugins/invert.cpp, plugins/single_plugins/switcher.cpp, plugins/single_plugins/zoom.cpp, plugins/wobbly/wobbly.cpp, src/api/compositor-surface.hpp, src/api/compositor-view.hpp, src/api/core.hpp, src/api/nonstd/noncopyable.hpp, src/api/opengl.hpp, src/api/render-manager.hpp, src/api/view-transform.hpp, src/api/view.hpp, src/core/core.cpp, src/core/gldebug.hpp, src/core/opengl.cpp, src/main.cpp, src/output/render-manager.cpp, src/view/compositor-view.cpp, src/view/surface.cpp, src/view/view-3d.cpp, src/view/view.cpp
We now bind the proper context before each rendering operation and clean up gl state after rendering is done.
Fixes #104 #44
=> Properly manage GL state

plugins/cube/cube.cpp, plugins/cube/cube.hpp, plugins/cube/cubemap.cpp, plugins/cube/simple-background.cpp, plugins/cube/skydome.cpp
When skydome was selected with no image set, the cube would not
activate at all. This was partially because the background methods
were clearing the depth buffer and skydome was only doing this
when there was a texture set. This makes it so the background is
cleared to green when skydome or cubemap are selected but the
texture for them are not loaded.
=> cube: Fix cube when no skydome image is set

src/api/core.hpp, src/core/core.cpp
This is what [redshift-wlr](https://github.com/jonls/redshift/pull/663) uses
=> Add wlr_gamma_control_unstable_v1 support

src/output/wayfire-shell.cpp
Properly handle shell exclusive_zone requests which come before set_anchor. Fixes #149.
=> wayfire-shell: properly handle exclusive_zone requests

plugins/cube/cube.cpp, plugins/single_plugins/command.cpp, plugins/single_plugins/expo.cpp, plugins/single_plugins/fisheye.cpp, plugins/single_plugins/grid.cpp, plugins/single_plugins/idle-inhibit.cpp, plugins/single_plugins/invert.cpp, plugins/single_plugins/oswitch.cpp, plugins/single_plugins/rotator.cpp, plugins/single_plugins/vswitch.cpp, src/api/plugin.hpp, src/core/seat/cursor.cpp, src/core/seat/keyboard.cpp, src/core/seat/touch.cpp, src/core/wm.cpp, wayfire.ini.default
Command now supports a new kind of binding, with the prefix `repeatable_`. This will make the command to be executed repeatedly after a certain delay. Works for key- and button activated commands.
Still TODO: enable the user to configure the repeat rate and delay. Do we reuse core options? Or do we add specific options for the command plugin?
=> Add option to repeat key/button binding for command

src/core/seat/cursor.cpp, src/core/seat/input-manager.hpp, src/core/seat/keyboard.cpp, src/core/seat/touch.cpp, wayfire.ini.default
- remember which actual key activated a modifier binding (so that an [xcape](https://github.com/alols/xcape)-style plugin would be able to distinguish between left and right shift to do shifts-as-parens)
- add a configurable timeout for modifier bindings (nothing happens when a modifier is held for too long)
- use xkbcommon to apply the keymap to the modifier keys (so any xkb_options like swapping Ctrl and Caps Lock or the choice of Super would apply) (note: rootston uses xkbcommon for *everything* in bindings)
=> Improve modifier bindings

src/api/view.hpp, src/view/view.cpp
Calling zwlr_foreign_toplevel_handle_v1_close() from a client using
the foreign toplevel protocol did not work because it was not
implemented. Now clients can request toplevels be closed and it
will actually work. Fixes #174.
=> Implement foreign toplevel close handler

plugins/single_plugins/grid.cpp, plugins/single_plugins/move.cpp, plugins/single_plugins/resize.cpp, plugins/single_plugins/snap_signal.hpp, plugins/wobbly/wobbly.c, src/api/signal-definitions.hpp, src/api/view.hpp, src/view/view.cpp, src/view/xdg-shell.cpp, src/view/xdg-shell.hpp
Fixes #42.
Basically, we should indicate a tiled windowby tiling its edges. Maximize state is what comes from the client
itself.
@AdrianVovk Can you verify this fixes #42 (and breaks nothing else)?
=> view: add set_tiled() and tiled_edges

src/api/util.hpp
Looks like this problem might have been hidden by gnu libstdc++ including it somewhere, with llvm libc++ std::min/max are not found w/o `<algorithm>`
=> api: add missing include <algorithm> for std::min/max

src/core/output-layout.cpp, src/output/render-manager.cpp
=> [track-wlroots] output-layout, render-manager: track frame submission API changes

src/core/core.cpp
Sometimes, calling waitpid() would wait forever in the case where exit(0)
was called first. This was the case on amd cpu when switching to another
workspace and attempting to launch an app with keybinding. Fixes #224
=> Fix race condition when forking child to background

src/view/layer-shell.cpp
Instead of tripping assert(false):
```
frame #3: 0x0000000800c853b1 libc.so.7`__assert(func=<unavailable>, file=<unavailable>, line=<unavailable>, failedexpr=<unavailable>) at assert.c:51
frame #4: 0x00000000005664fb wayfire`anchor_to_edge(edges=0) at layer-shell.cpp:74
frame #5: 0x000000000056eb9c wayfire`wf_layer_shell_manager::set_exclusive_zone(this=0x00000000005d0730, v=0x000000081173ce00) at layer-shell.cpp:155
frame #6: 0x000000000056dc46 wayfire`wf_layer_shell_manager::arrange_unmapped_view(this=0x00000000005d0730, view=0x000000081173ce00) at layer-shell.cpp:250
frame #7: 0x0000000000566b08 wayfire`wayfire_layer_shell_view::wayfire_layer_shell_view(this=0x000000081173ce00, lsurf=0x000000080b919c00) at layer-shell.cpp:314
…
```
=> layer-shell: actually check for anchoring to 0 edges

src/core/output-layout.cpp
Regressed by https://github.com/swaywm/wlroots/pull/1763 but probably an improvement even with wlroots 0.6.0.
=> Unbreak with wlroots master

plugins/single_plugins/meson.build, plugins/single_plugins/vswipe-processing.hpp, plugins/single_plugins/vswipe.cpp, src/api/geometry.hpp, src/api/signal-definitions.hpp, src/core/seat/pointer.cpp, src/util.cpp
This is the proper nice trackpad workspace switching, like on macOS, not the cheap fake discrete gesture thing many people settle for with external programs like libinput-gestures. With this, you can "play around", move the viewport left-right-left-right, which is very relaxing, at least for me :)
=> vswipe: touchpad swipe support for switching workspaces

plugins/single_plugins/place.cpp
This was happening because cascade_x/y are initialized to 0 on plugin init
and rely on workarea change signal to update. However, this only happens if
place is loaded when wayfire starts. Fix this by initializing cascade_x/y
with the workarea.x/y on init. Fixes #304.
=> place: Fix window placement using cascade when place is loaded after wayfire starts

src/view/view.cpp
The decoration plugin calls set_decoration with a null frame
argument on unload which causes wayfire to crash. Handle this
case properly by resetting the frame and emitting decoration
changed signal. Fixes #311.
=> Avoid crash when calling set_decoration with null frame

meson.build
wlroots versions can still break on major version bumps. It would be helpful for users and packagers to know if they are compiling wayfire on an incompatible wlroots version.
=> Don't build on breaking wlroots version.

plugins/single_plugins/move.cpp, plugins/single_plugins/place.cpp, src/api/signal-definitions.hpp, src/api/view.hpp, src/view/compositor-view.cpp, src/view/view-impl.cpp, src/view/view-impl.hpp, src/view/xwayland.cpp
The mask contains information about whether or not to use the
position and size fields. Since size is determined by commit,
we only concern ourselves with the position here. This requires
[wlroots #1843](https://github.com/swaywm/wlroots/pull/1843). This fixes bugs with positioning xwayland surfaces
with and without place plugin enabled. Fixes #307.
=> xwayland: Use configure request mask to position surfaces

plugins/single_plugins/fisheye.cpp
This was causing fisheye to not activate until the second time
the binding is pressed after loading the plugin.
=> fisheye: Initialize activate variable

plugins/single_plugins/fisheye.cpp
This was causing fisheye to not start at all in some cases.
=> fisheye: Initialize hook_set variable

plugins/blur/blur.cpp, plugins/cube/cube.cpp, plugins/single_plugins/alpha.cpp, plugins/single_plugins/command.cpp, plugins/single_plugins/expo.cpp, plugins/single_plugins/fast-switcher.cpp, plugins/single_plugins/fisheye.cpp, plugins/single_plugins/grid.cpp, plugins/single_plugins/idle.cpp, plugins/single_plugins/invert.cpp, plugins/single_plugins/move.cpp, plugins/single_plugins/oswitch.cpp, plugins/single_plugins/resize.cpp, plugins/single_plugins/switcher.cpp, plugins/single_plugins/vswitch.cpp, plugins/single_plugins/wrot.cpp, plugins/single_plugins/zoom.cpp, plugins/tile/tile-plugin.cpp, src/api/bindings.hpp, src/api/output.hpp, src/core/seat/input-manager.cpp, src/core/seat/input-manager.hpp, src/core/seat/keyboard.cpp, src/core/wm.cpp, src/output/output-impl.hpp, src/output/output.cpp
When a client inhibits input, the compositor should send all
events, even those that match a binding.
=> Send bound events when input is inhibited

src/core/seat/pointing-device.cpp, src/core/seat/pointing-device.hpp, wayfire.ini.default
This adds support for libinput acceleration profiles (none, flat and adaptive) and sets it to the device default if none is set. This is mostly for an easy way to disable mouse acceleration, it's the same setting that is found in GNOME Tweaks for example.
There is a way to check if a device supports a profile before setting it but it doesn't seem necessary as it just seems to select the default in that case.
=> Support libinput acceleration profiles

src/view/xwayland.cpp
This was causing some clients to have pointer input offset
after going to windowed from fullscreen. Fixes #345.
=> xwayland: Don't add decoration size when sending configure

src/meson.build
This also introduces icondir variable to wayfire.pc file.
=> build: Add icondir variable to wayfire.pc

plugins/cube/cube-control-signal.hpp, plugins/cube/cube.cpp, plugins/single_plugins/idle.cpp
This allows a way for the idle plugin to set cube ease value
so deformation is included in the duration. Without this, the
deformation is enabled and disabled without a transition,
which isn't very pretty. This also fixes glitches every second
when the cube is rotating and seconds are enabled in the panel
clock.
=> screensaver: Add ease deformation to cube control

src/api/wayfire/object.hpp, src/api/wayfire/plugin.hpp, src/core/object.cpp, src/view/xwayland.cpp
This is an attempt at making the signals easier to use.
In general, when the object is destroyed, the signal will be disconnected automatically.
=> Safe signals

plugins/single_plugins/vswitch.cpp
`~base_option_wrapper_t()` is supposed to deregister the wrapper's listener from the updated handler list. But if the raw_option is moved out like that, the destructor doesn't do its job and boom we have a dangling pointer. And my gsettings plugin applying the duration tripped that.
IMO the option_wrapper should be safer — the zero-arg constructor should not exist, the destructor should throw if the raw option is zero, the raw option field should not be public…
=> vswitch: do not create dangling pointer by moving raw_option out of the wrapper

meson.build
By default on FreeBSD packages are installed under `/usr/local` and configuration is stored under `/usr/local/etc`.
This matches GNU autoconf default where `sysconfdir` under `prefix` by default.
=> Respect --prefix when looking for wayfire/defaults.ini

meson.build, src/meson.build
This is so programs like wcm can know where wayfire is looking for defaults. The file is $sysconfdir/wayfire/defaults.ini. Settings in this file will override the defaults found in the plugin xml files.
=> build: Add sysconfdir to generated .pc file

src/view/layer-shell.cpp
When newly created views are advertised attach-view signal,
the role was not yet set which causes problems for plugins
that are loaded when wayfire starts and use the role as a
conditional.
=> layer-shell: Set role in the constructor

src/api/wayfire/core.hpp, src/core/core-impl.hpp, src/core/core.cpp
This was previously an unused variable. It allows external
plugins to get the display string, since xwayland_get_display()
is not exported.
=> Set core xwayland_display string

src/view/surface.cpp
This can be triggered when moving a view to another output
with keycolor enabled or trying to move a compositor view,
such as in magnifier.
=> Fix crash introduced by transformer optimizations merge

metadata/cube.xml
This tells wcm to add a file chooser button to the relevant options.
=> cube: Add file hints to xml

metadata/idle.xml, plugins/single_plugins/idle.cpp, src/api/wayfire/signal-definitions.hpp, src/output/wayfire-shell.cpp, src/output/workspace-impl.cpp, src/view/view.cpp
This PR emits a view-fullscreen signal for the output and adds state to the view fullscreen signal. In addition, it renames autohide-panels signal to fullscreen-layer-focused, disable_dpms_on_fullscreen to disable_on_fullscreen and makes idle plugin listen for the fullscreen-layer-focused signal to disable idle completely if disable_on_fullscreen is enabled.
=> View fullscreen

.editorconfig, .github/workflows/ci.yaml, README.md, meson.build
In order to reduce issues between different C/C++ stacks, let's continuously test on a couple different ones. A mostly-GNU-but-musl one and a mostly-LLVM-but-glibc one was the best I could come up with. Here's [an example run](https://github.com/myfreeweb/wayfire/actions/runs/41498661).
- DEPENDS ON https://github.com/WayfireWM/wf-config/pull/21
- would be cool to also run static analysis in CI I guess (but where would it upload the nice HTML results?)
- maybe also test [wf-gsettings](https://github.com/myfreeweb/wf-gsettings) xml conversion :D
- maybe also enforce clang-format (when that happens) in CI (like Mozilla does for Firefox)
- this PR also fix some things found by clang analyzer (not tested running with these yet.. I don't run anything using wayfire-shell anyway..), I should …
=> Add CI (GitHub Actions)

src/api/wayfire/workspace-stream.hpp, src/output/render-manager.cpp
This allows plugins to know for which workspace the signal was called.
Plugins can use this to associate objects with workspaces.
=> Send workspace with stream pre and post signals

.github/workflows/ci.yaml
The previous naming scheme didn't accurately describe the jobs being run.
Would this impact any of the CI currently running in the project? It's just that the naming scheme bothered me. If you don't think it's necessary to fix, no problem, I can close the PR.
=> CI: fix the names used for the CI jobs

metadata/core.xml, metadata/idle.xml, wayfire.ini
This enables cube plugin by default and sets idle screensaver timeout.
=> Enable screensaver

src/view/surface.cpp
The wlroots changed the organization of the wlr_surface struct, which
led to breakage in the surface.cpp code. This commit fixes the
issue in wlr_surface_base_t::get_buffer(), which was the only place
affected (at least in regards to compile-time errors).
Fixes issue #432 
I have tested it on my machine, and wf-background and wf-panel both launched and worked perfectly.
EDIT: btw, this fix is only necessary in wlroots git, for now. I'd guess wlroots will make it necessary either in some 0.10.x revision or the 0.11.0 version. I don't know how that influences what you merge to master. And the CI builds seem to have failed because their version of wlroots isn't as recent.
=> view: fix wlr_surface usage due to upstream change

src/api/wayfire/render-manager.hpp, src/output/render-manager.cpp
There are at least two damage regions for a frame. We have client damage
which is the region of all surface damage for the output and the swap
damage which is the region passed to swap buffers. Typically we are
only interested in client damage but for purposes of plugins like
showrepaint, we need the swap damage to have a comprehensive view of
all damage happening on the output.
=> render-manager: Add get_swap_damage function

README.md
Currently wayfire is in the unofficial overlays but a request has been made to add it to the official tree.
Until it is accepted, I've added the two unofficial lists, wayfire-desktop (my personal managed overlay) and Guru (community managed overlay similar to AUR, but more reviewed, where wayfire is managed by me, and is kept up to date with my personal overlay, though with a bit of lag).
Thanks a lot for the amazing software :)
=> Added install instructions for gentoo

metadata/core.xml, src/api/wayfire/core.hpp, src/core/core.cpp, src/output/render-manager.cpp
[presentation-time](https://github.com/wayland-project/wayland-protocols/blob/master/stable/presentation-time/presentation-time.xml) can be used by e.g. `weston-presentation-shm` from Weston, which is suggested for [testing wlroots adaptive sync support](https://github.com/swaywm/sway/pull/5063) among other things.
I think `render_views` is the right (and only) place for this? Sway has another call in an optimized fullscreen scanout path, but we don't have that yet, right?
(Seems like we don't have a [repaint delay](https://ppaalanen.blogspot.com/2015/02/weston-repaint-scheduling.html) yet btw.. I'll look into that)
=> Low latency stuff: render delay, presentation time protocol

plugins/blur/blur-base.cpp, plugins/blur/blur.cpp, plugins/blur/blur.hpp, plugins/blur/bokeh.cpp, plugins/blur/box.cpp, plugins/blur/gaussian.cpp, plugins/blur/kawase.cpp
- Don't blur if opaque region occludes the bounding box of the view
- Scissor out the opaque region when we are blurring
- Use damage region for scissor to avoid unneeded blurring
=> blur: Implement some optimizations

src/output/plugin-loader.cpp
Plugins might depend on the grabbed state to clean up, so call fini
before ungrabbing.
=> plugin-loader: Call fini before ungrabbing

src/main.cpp
Otherwise, there may not be enough privs to drop gid.
=> main: set gid before uid

plugins/single_plugins/switcher.cpp
Found via some bizzare unloading thing (issue #475) + AddressSanitizer + RTLD_NODELETE (to see which plugin is to blame in the ASan trace — speaking of which, maybe a good idea to NODELETE.. always? in debug builds?).
=> switcher: implement fini()

meson.build
My glesv2.pc looks like this:
Name: glesv2
Description: GLESv2 library
Version: 20.0.2
Libs: -L/nix/store/cx6mp08wgy516yp5078i30ydj4g9hmah-libglvnd-1.2.0/lib -lGLESv2
Cflags: -I/nix/store/h1fhjwi5m2q09xi42f4rnaldm4q916xi-mesa-20.0.2-dev/include -I/nix/store/nvyl0ml7i69vqywdlmhjkdslc2l1yydh-libglvnd-1.2.0-dev/include
There's no includedir variable, so the header check always fails.
It would be possible to fix the check as follows:
meson.get_compiler('cpp')
.has_header('GLES3/gl32.h', dependencies: glesv2)
But I don't think it should actually be checked in this conditional at
all.  Having the header check means that even if I am building with
-Denable_gles32=true, Wayfire might decide to build with gles32
disabled.  It would be much better to error if enable_gles32 is true,
but the …
=> meson.build: drop GLES3/gl32.h check

plugins/cube/cubemap.cpp
Call OpenGL::render_end() where needed and unbind cubemap texture.
Without this, rotate cube crashes when no cubemap image is set.
Fixes #530.
=> cube: cubemap: Reset state on error

.github/workflows/ci.yaml
This makes it so ci will run even if the only files modified are in
metadata/ or proto/.
=> ci: Don't ignore any files

src/api/wayfire/core.hpp, src/core/core-impl.hpp, src/core/core.cpp
Create and expose a new core function get_view_at, which takes a point and
returns a view, or null if none is found. This is useful for plugins like
scale where it makes sense to be able to pick views while holding a grab.
=> core: Add get_view_at function to API

plugins/single_plugins/vswitch.cpp
Two small issues I noticed with the vswitch plugin while working on https://github.com/dkondor/wayfire/tree/scale
- need wf::CAPABILITY_CUSTOM_RENDERER
- set-workspace-request signal should only set carried_out == true if workspace switch was successful
Let me know if I should create an issue for these or a minimum example of the issue I had.
=> small fixes for vswitch

metadata/simple-tile.xml, metadata/wm-actions.xml, plugins/single_plugins/wm-actions.cpp, plugins/tile/tile-plugin.cpp
To resolve: https://github.com/WayfireWM/wayfire/issues/535
I have also noticed that when running alacritty and having `preferred_decoration_mode = server` the client decorations show up when I fullscreen the window for the second time. I think this is a bug unrelated to this PR but I cannot figure it out.
=> Move 'Toggle fullscreen' from simple-tile to wm-actions plugin

plugins/single_plugins/scale.cpp
this will use vswitch plugin if enabled
note: this requires to change grab_interface->capabilities to only include wf::CAPABILITY_GRAB_INPUT, otherwise they would clash with vswitch; as far as I understand this is OK since only this is actually used
There is some strangeness in during the workspace switch animation: the windows seem to "jump" a bit and the inactive ones stay transparent and revert later (instead of fading); I'll try to look into this more
the other crash I mentioned yesterday is fixed since then (it was caused by remove_transformers() and scale_data.clear() being reversed when deactivating the plugin
=> use request_workspace() to change workspaces

plugins/single_plugins/scale.cpp
I originally used it to keep track of views in the grid. Since find_view_in_grid() always goes through the list of views returned by get_views(), there is no need to keep this, we only need to save the number of rows, columns, and the number of views in the last row.
Alternatively, we could store the view pointers in the grid member for a very slight optimization of lookups. But I think removing it is more in line with the rest of the code.
=> No need for grid member variable anymore

metadata/scale.xml, plugins/single_plugins/scale.cpp
This is a personal preference, but I find this behavior better, since I can choose to initiate scale including all windows or only the current workspace.
This replaces the separate bool setting 'all_workspaces'. There are two activators, they can also be used to switch between the all workspaces / current workspace view as well.
=> Separate activator for all workspaces

meson.build
There are compilation errors with 0.10.0, so the minimum has been bumped
to the latest wlroots release.
=> Bump wlroots version.

metadata/scale.xml, plugins/single_plugins/scale.cpp
It is a preference thing, but I don't like the behavior that some views can become zoomed in or scaled up if their original size was smaller than the allocated space. It is easiest to see if there is only one, relatively small view open (e.g. gnome-calculator).
This commit disallows this behavior. This could be easily made into an option, but I'm not sure that level of customization is necessary :)
=> Scale zoom limit

config.h.in, meson.build, meson_options.txt, src/core/core.cpp, src/core/view-access-interface.cpp, src/view/view-impl.cpp, src/view/xwayland.cpp
This makes it so xwayland can be disabled at runtime when building against
wlroots that is built with xwayland. If the option is enabled and wlroots
was built without wlroots, the build will fail. Helpful for package maintainers
to avoid inconsistencies.
=> build: Add xwayland option

plugins/single_plugins/autostart.cpp, src/main.cpp, src/output/plugin-loader.cpp
Part 2 of #493. Implemented as proposed there. Also changes autostart to start wf-panel and wf-background from PATH rather than Wayfire’s prefix.
=> Support plugin installation outside of Wayfire’s prefix

plugins/single_plugins/fast-switcher.cpp, plugins/single_plugins/idle.cpp, plugins/single_plugins/switcher.cpp, plugins/single_plugins/vswitch.cpp, src/api/wayfire/workspace-manager.hpp, src/output/output.cpp, src/output/render-manager.cpp, src/output/workspace-impl.cpp, src/view/view-3d.cpp
This removes the wm_only flag from get_views_on_workspace which was an artifact
of when wayfire used libweston and a shadow discrepancy called for this hack.
=> Use transformed geometry when computing visibility if view is transformed

meson.build
Fixes #617, ported from Waybar as @jbeich suggested.
@jbeich, I hope this works for you?
=> meson.build: pick appropriate filesystem library

meson.build, src/meson.build
We need to disable our internal backtrace in this case.
=> meson: detect address sanitizer via CXXFLAGS

plugins/single_plugins/scale.cpp
This is a code style change, it uses a local reference instead of repeatedly looking up scale_data[view]; in my opinion, this is a bit cleaner and slightly more efficient (depending on the compiler).
=> Avoid multiple lookups in scale_data map

src/output/workspace-impl.cpp
This gives a chance for plugins to change view focus on workspace-changed.
=> workspace-impl: Emit workspace-changed signal at end of function

src/api/wayfire/core.hpp, src/api/wayfire/signal-definitions.hpp, src/core/core-impl.hpp, src/core/core.cpp, src/core/seat/input-manager.cpp, src/core/seat/input-method-relay.cpp, src/core/seat/input-method-relay.hpp, src/core/seat/keyboard.cpp, src/meson.build
This is a port of https://github.com/swaywm/sway/pull/4740
- seems to work the same as sway with squeekboard and the wlroots input-method example
- looks like no crashes anymore after I added all the `disconnect`s on listeners..
- style: `input->im_relay->setup_listeners()` called after the protocols are added is meh..
- too many `std::unique_ptr`?
=> Add input-method/text-input support

src/core/seat/input-method-relay.cpp, src/core/seat/input-method-relay.hpp
ASan detected a heap-use-after-free with both the use and the free
pointing at the `remove_if` thing (specifically the use was pointing at `input`,
aka `this->input`, so I guess `this` was freed).
Let's move the `remove_if` thing into a method on `relay`.
=> input-method-relay: hopefully appease ASan

README.md
The package is in the AUR and `pacman` can not install packages from there. A popular suggestion for installing from the AUR is `yay`.
=> Change Arch Linux installation procedure

src/view/xwayland.cpp
Helps with some weird crashes when unplugging outputs and views are unmapping.
=> xwayland: add guards in setter functions

metadata/blur.xml, plugins/blur/blur-base.cpp, plugins/blur/blur.hpp, plugins/blur/bokeh.cpp, plugins/blur/box.cpp, plugins/blur/gaussian.cpp, plugins/blur/kawase.cpp
This reduces the number of texture reads from 18 to 10 per pass,
while making the effects slightly stronger. This improves performance
because it uses hardware interpolation to read a weighted average of
more than one pixel at a time.
=> blur: Optimize gaussian and box shaders

plugins/single_plugins/switcher.cpp, src/api/wayfire/opengl.hpp, src/core/opengl-priv.hpp, src/core/opengl.cpp, src/output/render-manager.cpp
wlroots #2240 is a breaking change which would silently break Wayfire (because it changes some assumptions we make about how GL works). This PR attempts to fix that. There should be no code breakage for plugins, although some adjustments may be necessary.
~~On the way I managed to reproduce #636 and I think it should be fixed with this PR.
@damianatorrpm Can you confirm?~~
Fixes #98
Fixes #636
Fixes #703 
Also, this PR is wlroots-backwards-compatible, i.e it should work with current wlroots master too.
=> Prepare for wlroots #2240

metadata/input.xml, src/core/seat/input-manager.cpp, src/core/seat/input-manager.hpp, src/core/seat/keyboard.cpp
=> keyboard: Populate lock key states after creating context

proto/wayfire-shell-unstable-v2.xml
Renaming protocol name to `wayfire_shell_unstable_v2` fixed the include issue of qtwaylandscanner.
=> Fixed issues generating client header using qtwaylandscanner

plugins/wm-actions/wm-actions.cpp
Otherwise, we're in UB territory.
=> wm-actions: use correct signal type

plugins/single_plugins/vswitch.cpp
Special case of issue #676 
My comment from there:
I've just found that this issue can persist in the edge case when the same workspace is requested twice in quick succession. I've been able to see it with the scale plugin with this patch by @soreau
I've added a simple print statement and I think what is happening is that for the second request, vswitch::add_direction() is called with x == y == 0, and thus returns false (line 140). This sets carried_out to false in on_set_workspace_request() (line 204).
In workspace-impl.cpp, line 910, then it will test this and call set_workspace() that instantly sets the new workspace. But the vswitch animation is still running, so it ends up on the wrong workspace in the end.
Maybe, add_direction() could return true if x == y == 0, and thus the …
=> [vswitch] fix for requesting the same workspace multiple times

src/output/render-manager.cpp
This is because on the frame event, apps should start to repaint until the max_render_time kicks in.
Fixes #575
=> render-manager: send frame-done immediately on frame event

metadata/core.xml
Many users complaining about wayfire performance were able to fix the
problem by setting max_render_time to -1, which disables it. This option
is also supposed to be a per-output setting so it could cause problems
where there is more than one monitor with different refresh rates.
=> core: Disable max_render_time by default

src/core/seat/keyboard.cpp, src/core/seat/keyboard.hpp
=> keyboard: do not recreate xkb context if options didn't really change

metadata/wm-actions.xml
wm-actions is not a plugin which is important for being on by default.
Fixes #742
=> wm-actions: disable bindings by default

src/core/seat/seat.cpp, src/core/seat/seat.hpp
This can cause crashes in some clients, if the drag icon is already
mapped when the drag starts.
=> seat: force map drag icons when starting drag

metadata/wm-actions.xml, plugins/single_plugins/expo.cpp, plugins/tile/tree.cpp, plugins/vswitch/vswitch.cpp, plugins/wm-actions/wm-actions.cpp, src/api/wayfire/plugin.hpp, src/api/wayfire/signal-definitions.hpp, src/api/wayfire/view.hpp, src/output/render-manager.cpp, src/output/workspace-impl.cpp, src/view/layer-shell.cpp, src/view/view.cpp, uncrustify.ini
This PR adds basic support for sticky views. Sticky views are very similar to
how layer-shell surfaces were behaving previously (in fact, layer-shell surfaces
are now sticky). They do not change coordinates when changing their workspace (so their
coordinates are always on the current workspace), and some plugins need to be careful
when dealing with such views.
Since this is a strange category of views, I expect a few issues to pop up. I'd welcome
reports about that.
To use the feature, enable `wm-actions/toggle_sticky` and either click on a view or if
using a keybinding, the currently focused view will be made (un)sticky.
Known issues:
- Sticky views appear only halfway in Expo (won't fix)
Fixes #405
=> Add support for sticky views

src/core/seat/pointer.cpp, src/core/seat/tablet.cpp
This makes it so the cursor is reset to default when not over any surface.
This can happen if there is no background application running, for example.
=> Set cursor to default pointer when over no surface

src/view/xwayland.cpp
Doesn't fix any existing issue, but this is nice in general.
=> xwayland: make set_geometry() send a single configure to the client

src/output/output.cpp
There are currently no signals emitted when a view or output loses focus.
This emits focus-view with view set to null when an output loses focus.
Useful for scale to know to set inactive opacity when scale is active
on more than one output.
Cherry-picked from #555
=> Emit focus-view signal when focus is lost

src/core/seat/keyboard.cpp
We shouldn't convert const char* to char*. This fixes a compiler warning.
=> Make char* argument const

src/output/render-manager.cpp
Flip headless backend to be right-side-up while we wait for wlroots
swapchain work to be merged.
=> render-manager: Use normal transform type for headless path

plugins/single_plugins/alpha.cpp, plugins/window-rules/lambda-rules-registration.hpp, plugins/window-rules/window-rules.cpp
- window-rules: destroy global object
- alpha: fix shutdown crashes
Fixes the shutdown crash reported by @dkondor
=> fix window rules destruction

plugins/scale/scale.cpp
I think making it the same as the initial animation makes sense (for ex. I want faster animation and fast scale startup but slow fade looks pretty bad). If anyone wants to control the two animation durations separately, then a PR would be welcome.
=> scale: make fade animation use the animation duration

src/api/wayfire/signal-definitions.hpp, src/api/wayfire/view.hpp, src/view/view-impl.cpp, src/view/view-impl.hpp, src/view/view.cpp, src/view/xdg-shell.cpp, src/view/xdg-shell.hpp, src/view/xwayland.cpp
These mechanisms are available for xdg-shell and Xwayland.
The idea is that plugins send a ping request to the client, and it should respond within 10 seconds. If it does, nothing happens, otherwise, the plugin(s) can guess that the client is unresponsive and thus present the user with an option to kill that client.
Fixes #140
@AdrianVovk I have not tested this API yet, however it is fairly simple so I hope it works fine.
=> view: add ping and ping-timeout support

src/api/wayfire/core.hpp, src/api/wayfire/plugin.hpp, src/core/core-impl.hpp, src/core/core.cpp, src/core/output-layout.cpp, src/core/seat/cursor.cpp, src/core/seat/input-manager.cpp, src/core/seat/input-manager.hpp, src/main.cpp, uncrustify.ini
- uncrustify: fix wrongly added newline between enum class and ident
- core: add information about compositor state to API
- core: refresh device mappings after the backend has started
This should fix #671, @myfreeweb do you have a way to verify the crash is fixed?
=> add compositor stages

src/core/core.cpp
The mouse pointer position was being set during output initialization,
before the final outputs' positions were known, which was making the cursor
jump outputs, the first time it was moved, in some cases. This patch sets
the position after the outputs have been fully laid out. Additionally,
we make the default output the leftmost, topmost one.
=> core: Initialize pointer position to center of leftmost, topmost output

plugins/common/wayfire/plugins/common/move-snap-helper.hpp, plugins/single_plugins/grid.cpp, plugins/single_plugins/move.cpp, src/api/wayfire/geometry.hpp, src/api/wayfire/plugin.hpp, src/api/wayfire/signal-definitions.hpp, src/api/wayfire/view.hpp, src/core/output-layout.cpp, src/util.cpp, src/view/view-impl.hpp, src/view/view.cpp, src/view/xdg-shell.cpp, src/view/xwayland.cpp
- view: consider workspaces for tiling and fullscreening
- output-layout: fix moving views when output is disconnected
- grid: add support for maximizing on a workspace
- view: store windowed geometry before starting move
Fixes #606
Fixes #625
=> fix view geometry with multiple outputs and workspaces

plugins/vswitch/vswitch.cpp, plugins/vswitch/wayfire/plugins/vswitch.hpp, src/api/wayfire/plugin.hpp, src/api/wayfire/signal-definitions.hpp, src/output/gtk-shell.cpp, src/output/workspace-impl.cpp, src/view/view.cpp, src/view/xwayland.cpp
- core: make minimized layer behave like the others
- view: make focus_request work better
- vswitch: switch workspace before starting animation
This has been requested in IRC before, and in #178.
With these changes, minimized views are "per-workspace". Clicking on a minimized view in wf-panel will go to the view's original workspace.
Fixes #178 (the view is focused on its original output and we switch to its original workspace).
@AdrianVovk if you want to override this behavior, you can create a plugin to do so:
1. Connect to view-focus-request.
2. If the view is on the focused output, let core handle the request.
3. Otherwise, set carried_out to false to block other plugins and core.
4. Move the view to the output and workspace you want it to be.
5. Call view->focus_request() there. …
=> make minimized views per-workspace

src/api/wayfire/plugin.hpp, src/api/wayfire/view.hpp, src/output/output.cpp
Also make refocus use the last focused view, not the topmost one.
Fixes #664
=> view: add last_focus_timestamp

src/api/wayfire/signal-definitions.hpp, src/view/view.cpp
This is the same way view-self-request-focus used to work.
=> view: make sure view-focus-request is emitted on the view and on core

src/core/seat/tablet.cpp, src/core/seat/tablet.hpp
It will auto-disconnect, avoiding a crash with tablet input.
=> tablet: use signal_connection_t instead of signal_callback_t

src/api/wayfire/opengl.hpp, src/core/opengl.cpp
For plugin usage; maybe also `find_uniform_loc` should be exposed in the outer non-private object but for now I just need this one
=> Add OpenGL::program_t::uniform3f

src/view/xwayland.cpp
Even if they have transient-for set. Fixes #846
=> xwayland: avoid setting surfaces with NORMAL type as OR

metadata/blur.xml, plugins/blur/blur-base.cpp, plugins/blur/blur.cpp, src/output/render-manager.cpp
- blur: add option to configure which views should be blurred
- blur: calculate blur region
The new option is called `blur/blur_by_default` and has type criteria. If you want a bit more efficient blur, set only views that you want to blur.
I believe we can close #669 with this PR.
=> blur optimizations

src/output/render-manager.cpp
Reverts WayfireWM/wayfire#790
Swapchain has been merged in wlroots master, we need this code.
If anyone is using Intel, there may be bugs (affects newer GPUs): https://github.com/swaywm/wlroots/pull/2240#issue-426128653
At least there are workarounds in the mentioned wlroots PR.
=> Revert "render-manager: Use normal transform type for headless path"

metadata/workarounds.xml, src/core/core.cpp, src/output/output.cpp, src/view/view-impl.cpp
Fixes #869
Wayland does not have the concept of modal and non-modal dialogs. This might come as a future extension to the xdg-shell protocol. In the meantime, we can provide users with an option to choose whether dialogs should all be modal (as it was up to now) or non-modal.
If all dialogs are modal: whenever a dialog is open, it will always be focused, and the main window will not be able to receive keyboard focus until the dialog is closed.
If all dialogs are non-modal: dialogs are still kept on top of their respective main window. However, the main window can still be focused. Some toolkits like Qt apply certain hacks - Qt will ignore events on the main window if it has opened a dialog it thinks is modal.
Overall, setting `workarounds/all_dialogs_modal` to `true` (which is the …
=> workarounds: add support for non-modal dialogs.

plugins/single_plugins/switcher.cpp, src/view/layer-shell.cpp
Since assert() is a macro, building wayfire with -DNDEBUG leads to the
entire expression being compiled out, which means it's never run. This
made it so that once the switcher plugin was launched, it wouldn't quit.
Fixes #879
=> switcher: remove expression with side effects from assert().

src/core/output-layout.cpp
This makes it possible for plugins like primary-output-switch to restore views from NOOP outputs.
Will merge this after 0.6.0 release because it may have other unintended consequences, so this needs more testing.
=> output-layout: ensure noop output is in the output list when it exists

plugins/blur/blur.cpp, plugins/cube/cube.cpp, plugins/scale/scale.cpp, plugins/single_plugins/command.cpp, plugins/single_plugins/expo.cpp, plugins/single_plugins/fast-switcher.cpp, plugins/single_plugins/fisheye.cpp, plugins/single_plugins/grid.cpp, plugins/single_plugins/idle.cpp, plugins/single_plugins/invert.cpp, plugins/single_plugins/move.cpp, plugins/single_plugins/oswitch.cpp, plugins/single_plugins/resize.cpp, plugins/single_plugins/switcher.cpp, plugins/single_plugins/wrot.cpp, plugins/tile/tile-plugin.cpp, plugins/vswitch/wayfire/plugins/vswitch.hpp, plugins/wm-actions/wm-actions.cpp, src/api/wayfire/bindings.hpp, src/api/wayfire/output.hpp, src/api/wayfire/plugin.hpp, src/core/seat/bindings-repository.cpp, src/core/seat/bindings-repository.hpp, src/core/seat/hotspot-manager.cpp, src/core/seat/keyboard.cpp, src/core/seat/pointer.cpp, src/core/wm.cpp, src/output/output-impl.hpp, src/output/output.cpp
~~Still WIP, but should eventually:~~
fix #655
fix #833
This PR adds the long-awaited support for calling arbitrary plugins via their activator bindings. Example patch to make Expo activate on all workspaces at the same time (although I recommend actually doing an external plugin which activates all Expos on all outputs):
```diff
diff --git a/plugins/single_plugins/expo.cpp b/plugins/single_plugins/expo.cpp
index 2d4e11b6..8092898b 100644
--- a/plugins/single_plugins/expo.cpp
+++ b/plugins/single_plugins/expo.cpp
@@ -35,8 +35,23 @@ class wayfire_expo : public wf::plugin_interface_t
return wf::point_t{x, y};
}
-    wf::activator_callback toggle_cb = [=] (auto)
+    wf::activator_callback toggle_cb = [=] (auto ev)
{
+        // Avoid self-loop
+        if (ev.source != …
```
=> programmable activators

plugins/decor/decoration.cpp
When wayfire starts with decoration plugin loaded, newly created views are decorated.
If the plugin is unloaded, the decorations are destroyed. This patch makes it so
existing views are decorated when the plugin is loaded.
=> decoration: Add decorations to views on init

metadata/wm-actions.xml, plugins/wm-actions/wm-actions.cpp
This is a simple implementation that relies on minimize to show the desktop.
Closes #340.
=> wm-actions: Add binding to show desktop

plugins/window-rules/window-rules.cpp
This PR enables the `window-rules` plugin to auto-reload all the rules when config file is modified without having to restart wayfire.
=> Reload window-rules on config change

metadata/core.xml, src/core/wm.cpp, src/core/wm.hpp
This addresses the second part of my issue #891 by allowing a view to be focused by a modifier + mouse click. In my opinion, this behavior is more consistent. Also, this ensures that the clicked view receives the modifier state (since it is always focused).
I've implemented this as an option, with the old behavior being the default.
Depends on https://github.com/WayfireWM/wf-config/pull/36
Currently, click-to-focus only works for mouse clicks without keyboard modifiers. If a modifier is held down, the necessary button binding in the focus handler does not match, so the focus does not change. The view under the mouse receives the mouse click, but not the state of the keyboard modifiers (since it never receives keyboard focus).
This commit adds an option to essentially ignore pressed …
=> core: Add option to focus a view on mouse click even if modifiers are pressed

plugins/window-rules/view-action-interface.cpp
Before this change, all move and resize window rules would wrongly log this error:
"View action interface: Unsupported action execution requested. Name: "
=> Error no longer logged for move and resize window rules

metadata/invert.xml, plugins/single_plugins/invert.cpp
This makes the invert plugin only operate on black/white keeping the hue as is.
=> Invert without changing colors

src/core/seat/pointer.cpp, src/core/seat/seat.cpp, src/core/seat/seat.hpp, src/core/seat/tablet.cpp, src/core/seat/touch.cpp, src/view/view-impl.hpp, src/view/xwayland.cpp
Fixes #666
Unfortunately, this does not work yet.
The problem is restacking - the `xwayland_bring_to_front` function doesn't seem to do anything.
I'll try to look into it later, but any hints why it doesn't work are much appeciated.
=> core: put xwayland surfaces on top when giving them pointer focus

plugins/scale/scale.cpp
Signed-off-by: epsilonKNOT <floss@bsd.ac>
---
Possibly closes https://github.com/WayfireWM/wayfire/issues/797
---
~~after pondering, it seems like the sorting algo will depend on the final displaying algorithm. `wcnt` = number of windows per row, which is currently set to `ceil(sqrt(views.size()))`, should be changed to reflect the actual number of windows per row.~~
I should spend more time reading rather than getting high and writing code, this was right beside the code where i was tinkering...
=> better sorting algorithm for scaling

plugins/scale/scale.cpp, src/core/seat/keyboard.cpp
- keyboard: correctly handle grabs when forwarding to client
- scale: drop `input_release_impending`
Core was handling keyboard events in a wrong way, and was not correctly calculating when a key is consumed by a plugin.
With that fix, scale no longer needs to keep track of `input_release_impending`, since `KEY_ENTER`/`KEY_ESC` are not forwarded to clients (because they happened during a grab).
Also, this means that scale can deactivate immediately, which also fixes the problem of skipping a workspace when using vswitch bindings while exiting scale.
=> fix handling of keyboard when grab is active

metadata/workarounds.xml, src/output/render-manager.cpp
Some time ago, @myfreeweb added the option for repaint delay. While it is good enough for basic scenarios, it is in general very difficult to say what the maximum render time will be (it depends on plugins, etc.).   This is why I thought it might be interesting to experiment with an algorithm which adjusts the repaint delay dynamically. This is off by default, and can be enabled with `workarounds/dynamic_repaint_delay`.
The basic idea is this: the user sets a very low `max_render_time`, maybe even 0. Wayfire's algorithm then tries to increase or decrease delay based on whether the last frames were on time or not.
The goals when designing this algorithm were: The algorithm should periodically try to increase the delay (faster at startup, slower later), however, this should not be often …
=> render-manager: add an algorithm for smarter repaint delay

src/api/wayfire/nonstd/wlroots-full.hpp, src/core/seat/input-manager.cpp, src/core/seat/tablet.cpp, src/core/seat/tablet.hpp
All events are simply forwarded to the currently focused view.
@psstoyanov This is simply an old patch I rebased on top of master, because of lack of hardware I have never tested this so it might not work.
Fixes #732
=> input: implement basic tablet pad support

src/core/seat/input-manager.cpp
=> input-manager: skip hidden views when finding the input surface

src/view/xdg-shell.cpp, src/view/xdg-shell.hpp
As discussed in #923, there are certain races when a view is resized multiple times, for example in the following case:
1. Client has size 100x100
2. We send a configure for 50x50. Set pending compositor size to 50x50.
3. Clients commits before ACKing 50x50, reset pending compositor size to 100x100.
4. Plugin tries to resize to 100x100 again, but this is the same as compositor pending size (per 3.) so this fails
5. Client commits again and ACKs our configure request and has size 50x50.
In the end, the client has the wrong size. The solution is to keep track of which the last configure sent by Wayfire is, and on commit, to check if the client has caught up with us already.
=> xdg-shell: keep track of last serial

src/api/wayfire/signal-definitions.hpp, src/core/core.cpp, src/core/output-layout.cpp, src/main.cpp
- output-layout: deinitialize noop output on renderer destroy
- core: add startup-finished signal to signal the start of main loop
The new signal can be used to override Wayfire's main loop.
~~An example plugin is coming soon.~~ See https://github.com/WayfireWM/wayfire-plugins-extra/pull/74
=> startup finished signal

plugins/scale/scale-title-filter.cpp
This is a fix for the first issue in #980  -- key repeat can become stuck if scale ends while a key is pressed.
=> scale: fix title filter being stuck

plugins/scale/scale.cpp
With this change, the "scale-end" signal is emitted earlier, when scale starts to exit (whenever possible). This way, filters that display an overlay (such as the title filter) can deactivate earlier instead of only after the animation is finished.
This fixes the second issue in #980 (overlay displayed too long).
=> scale: emit end signal earlier

src/default-config-backend.cpp, src/main.cpp
Support setting the configuration file via `WAYFIRE_CONFIG_FILE`, to match WCM.
Also, export the used configuration file, so that WCM can pick up the configuration in Wayfire, even if
it is set via the command line.
=> config: support environment variable for config file

plugins/animate/fire/fire.cpp, src/api/wayfire/core.hpp, src/api/wayfire/nonstd/wlroots-full.hpp, src/api/wayfire/nonstd/wlroots.hpp, src/api/wayfire/opengl.hpp, src/core/core.cpp, src/core/opengl.cpp, src/core/shaders.tpp, src/view/surface.cpp, src/view/view.cpp
This is not a breaking change, because all the needed calculations can be put behind the texture_t and program_t abstractions (the calculations are done inside get_pixel()).
Fixes #553
=> core: add support for wp-viewporter

metadata/fast-switcher.xml, plugins/single_plugins/fast-switcher.cpp
Similarly to how it is possible in switcher. This makes fast-switcher more flexible. E.g. I often "overshoot" the view I'd like to switch to, and currently that requires me to go one more circle.
=> fast-switcher: allow switching backwards

plugins/decor/deco-subsurface.cpp, src/api/wayfire/plugin.hpp, src/api/wayfire/signal-definitions.hpp, src/api/wayfire/surface.hpp, src/api/wayfire/view.hpp, src/view/surface.cpp, src/view/view.cpp
These are useful for plugins which have subsurfaces. In this way, they
can emit the unmap signal at the correct time.
Fixes #837
=> subsurfaces: add new subsurface-added/removed signals

src/api/wayfire/core.hpp, src/api/wayfire/plugin.hpp, src/main.cpp
They are visible for all plugins.
Fixes #658
=> core: add command line arguments

src/view/layer-shell.cpp
Implementation for https://github.com/swaywm/wlr-protocols/pull/100 -- requires https://github.com/swaywm/wlroots/pull/2555 to actually work.
Only a value of 1 is interpreted as a request for exclusive focus. Other > 0 values result in normal focus semantics.
=> layer-shell: adjust keyboard-interactivity

src/api/wayfire/signal-definitions.hpp
It is currently not consistent with what is used in cursor.cpp
=> signal-definitions: use correct name for pointer_motion_absolute

plugins/scale/scale-title-filter.cpp
Fixes #1008 -- seems that I was using the wrong function to get the damage, since `get_swap_damage()` returns scaled regions
=> scale-title-filter: fix damage handling on scaled output

metadata/input.xml, src/core/seat/pointing-device.cpp, src/core/seat/pointing-device.hpp
This pull request adds [middle click emulation](https://wayland.freedesktop.org/libinput/doc/1.11.3/middle_button_emulation.html) support into the config like so:
```ini
[input]
middle_emulation = true
```
=> Add middle_emulation for middle click emulation

src/view/layer-shell.cpp
Fixes #908
This can happen if an output is plugged in and unplugged immediately (possibly on the noop output): the compositor will close the (unmapped) layer-surface, it may commit before receiving the close request, but its output is set to `nullptr` by output-layout (since the output was destroyed).
=> layer-shell: ignore unmapped layer-shell view commits without output

plugins/window-rules/view-action-interface.cpp, plugins/window-rules/view-action-interface.hpp
With this rule, window-rules can move the view to a given workspace.
Example:
```
rule1 = on created if app_id is "terminator" then assign_workspace 1 1
```
Note: the window-rules plugin should come later than the place plugin (if it is enabled), otherwise, there might be a conflict between these two.
Fixes #588
=> window-rules: add assign-workspace rule

metadata/grid.xml, plugins/single_plugins/grid.cpp
I have started to experiment a bit with a crossfade animation instead of the default move+resize for grid.
There are still a few things left that should be fixed, but I think it should already be much smoother than the current animation.
~~Opening as a draft because it seems easy to get Grid into a state where it flips between fullscreen and unfullscreen each frame, making the window unusable. Will investigate further on that.~~ Seems a bug in GTK3, it happens on gnome too.
Note if someone is testing this: it requires the dynamic-list branch of wf-config, otherwise, it won't compile. This is necessary for a small addition I made there.
Fixes #991
=> grid crossfade

src/view/layer-shell.cpp
Fixes a crash when hotplugging a monitor.
@szbergeron This is the fix I talked about on IRC.
=> layer-shell: destroy anchored area when view is removed from its output

metadata/wrot.xml, plugins/single_plugins/wrot.cpp, src/view/view-3d.cpp
While working on #996 I've noticed [this TODO](https://github.com/WayfireWM/wayfire/blob/faab309a9122b758f5edd164a7bc2748ce3e4f52/src/view/view-3d.cpp#L229) and realized that I can provide a solution. This is possible since the "3D" transform in this case is actually mapping a 2D object to a 2D canvas, so it is not losing information (except in the case when the view is turned perpendicular to the screen).
The first commit is actually the inverse of the transform, the second commit adds a simple plugin to demonstrate that it is working -- I'm actually not sure if this plugin should go in the main plugin collection (maybe it could be merged with the 2D "wrot" plugin?).
=> Invert 3d transformer

metadata/scale.xml, plugins/common/wayfire/plugins/common/cairo-util.hpp, plugins/scale/meson.build, plugins/scale/scale-title-filter.cpp, plugins/scale/scale-title-overlay.cpp, plugins/scale/scale-title-overlay.hpp, plugins/scale/scale.cpp, plugins/scale/wayfire/plugins/scale-signal.hpp, plugins/scale/wayfire/plugins/scale-transform.hpp
This is an implementation for #990 
Some notes:
- I've made this part of the title filter plugin, since I'm unsure if it makes sense to add and extra plugin and also to share code more easily; maybe the title filter plugin could be renamed to "Scale addons" or something similar?
- The helper classes: `cairo_text_t` and `view_overlay` could be part of some common tools. This way, other plugins can re-use them to render text and to add overlays to views.
- The `view_overlay` transformer is not efficient in its current form, since there is no need to copy the view's texture to a new framebuffer. I wonder if there is a way to add a transformer that renders to the latest framebuffer without copying that I missed, or if it would make sense to add this functionality?
- I could not find an easy …
=> Show views' title as an overlay during scale

plugins/common/wayfire/plugins/common/move-drag-interface.hpp, plugins/scale/scale.cpp, plugins/single_plugins/expo.cpp, plugins/single_plugins/move.cpp
This is necessary because for adjusting the end position, we need to know the relative grab locations for all views.
Fixes #1041
cc @damianatorrpm
=> move-drag-interface: add information about all views in done signal

src/core/core.cpp, src/view/xwayland.cpp
Seems to be a necessary fix for JetBrains IDEs, see https://github.com/swaywm/wlroots/pull/2605
=> core, xwayland: support views which do not accept keyboard focus

metadata/scale-title-filter.xml, plugins/scale/scale-title-filter.cpp
Fixes #1021 -- made it an option if filter should be shared among outputs + keys are ignored if scale is not running on the current output.
Notes:
- if the sharing option changes while scale is running, the filter will be reset
- If the active output changes while a key is held down, it is not handled (but it is handled when the key is released)
I think dealing with the above cases in a special way would add a lot of complexity for a very little benefit.
=> Scale filter multi outputs

metadata/autostart.xml, metadata/command.xml, metadata/expo.xml, plugins/single_plugins/autostart.cpp, plugins/single_plugins/command.cpp, plugins/single_plugins/expo.cpp
Use the new compound_list option type in wf-config for easier parsing of options which are generated on-the-fly by matching options
with prefixes in the same section.
=> dynamic lists

plugins/single_plugins/preserve-output.cpp, src/core/output-layout.cpp, src/view/view-impl.cpp
- view: reset decoration on unmap
- preserve-output: store the output's workspace too
- output-layout: fix shutdown handling
- preserve-output: fix reference counting by using shared_data helpers
=> multi-output fixes

plugins/animate/basic_animations.hpp, plugins/scale/scale.cpp, src/api/wayfire/plugin.hpp, src/api/wayfire/view-transform.hpp, src/view/view-3d.cpp
Fixes #1046 
Depends on #1050 and ~~#1051~~ #1056 -- otherwise the results can look strange.
Note: this is not a perfect solution, since the bounding box of the view's WM geometry can grow excessively with multiple transforms (e.g. two 45 degree rotations will result in the bounding box growing twice as wide). A better way could be to transform each of the corner points (but that only works for transforms that preserve straight lines -- so far all transforms do that).
=> Scale: ensure transformed views fit in their slot

meson.build
The 0.7.x branch contains more commits to keep compatibility with wlroots 0.12, they are not meant for master.
=> Bump Wayfire version to 0.7.0 in master

plugins/common/wayfire/plugins/common/workspace-stream-sharing.hpp, plugins/cube/cube.cpp, plugins/tile/tile-plugin.cpp, src/api/wayfire/plugin.hpp, src/api/wayfire/signal-definitions.hpp, src/api/wayfire/workspace-manager.hpp, src/output/render-manager.cpp, src/output/workspace-impl.cpp
This PR adds support for changing the number of workspaces on-the-fly. The user can now simply edit `wayfire.ini` and set `vwidth/vheight`, and the changes will be applied immediately. If the change reduces the number of workspaces, core will make sure that the views on the now-removed workspaces are moved to the remaining workspaces.
For people wishing to write their own plugins, this PR also adds support for changing the number of workspaces from a plugin on a per-output basis. A proof-of-concept can be found here: https://github.com/ammen99/wayfire-plugins/blob/dyn-ws/src/dynamic-workspace-switch.cpp
This is a new plugin which works the following way: initially, Wayfire has only one workspace 1x1 (hardcoded in the plugin). The plugin also provides hardcoded bindings `<super>KEY_J` and …
=> api: add support for dynamically changing the number of workspaces

src/util.cpp
When a timer is fired but not repeated, we should destroy the event source, and make sure `is_connected` returns false.
=> util: make sure to disconnect if timer is not repeated

src/core/opengl.cpp
The only place left is output mirroring.
Fixes #1098
@jbeich does this make Wayfire start again?
=> opengl: don't use wlr_renderer functions

src/default-config-backend.cpp
This pull request makes Wayfire only watch the config directory for changes related to the Wayfire config file. This prevents sudden config reloads when using other screen managers like `kanshi` when an application modifies the config folder.
=> Only inotify the config file

src/view/xdg-shell.cpp
Fixes #1125 
It seems that for xdg_popups, wlroots will immediately send a configure event in response to a commit request (see [here](https://github.com/swaywm/wlroots/blob/c740fccc9dd0913908c0632c10f8c6d10b2b1ca4/types/xdg_shell/wlr_xdg_surface.c#L372) and [here](https://github.com/swaywm/wlroots/blob/c740fccc9dd0913908c0632c10f8c6d10b2b1ca4/types/xdg_shell/wlr_xdg_positioner.c#L154)), so there is no chance to update the position then (the configure event might be sent with the wrong position).
This can be avoided by adjusting the position while creating the popup. This is what [sway is doing](https://github.com/swaywm/sway/blob/152a559e30244e64d4d61b9c87db442dfa04ee52/sway/desktop/xdg_shell.c#L107) if I understand correctly. Since the client is required to supply the requested size in …
=> wayfire_xdg_popup: calculate position during initialization

meson.build, meson_options.txt, src/main.cpp, src/meson.build
This should help users that want coredump generation to work correctly.
Systemd-coredump should work when this option is disabled, but I haven't
tested systemd-coredump specifically.
=> build: make stacktrace configureable

README.md
For new users `pkg install wayfire` is not enough as `wayfire` unless configured would just show blank/black screen. Expand the command line to include recommended addons in order to have something usable out of the box.
I'll package if something is recommended but missing.
=> readme: update install instructions on FreeBSD

src/api/wayfire/plugin.hpp, src/api/wayfire/view.hpp, src/view/view.cpp
Allow plugins to get the framebuffer containing the snapshot of the view.
=> core API: Add get_snapshot

src/core/seat/hotspot-manager.cpp, src/core/seat/hotspot-manager.hpp
Fixes #1141 
Using a boolean flag to determine whether or not an event has already been fired by the cursor entering the hotspot area. Cursor must leave the area before another event can be fired.
=> Prevent multiple events being fired by hotspot area

plugins/blur/blur.cpp
When doing region math, sometimes we get an empty region which
means we try to allocate 0 sized buffer in both dimensions. Fix
this by checking the region is not empty before painting.
=> blur: Ignore empty regions when painting

.github/workflows/ci.yaml, meson.build, src/api/wayfire/nonstd/wlroots-full.hpp
Make wayfire compile with wlroots-master
@soreau Some time ago you asked whether we should update the version number immediately after release ... what about having a version 0.7.999 to indicate we're in development?
=> update meson.build and wlroots submodule

src/output/workspace-impl.cpp
This avoids glitchy rendering of the other views on the sublayer when
bring_to_front raises it.
=> workspace-impl: Damage all views in sublayer

src/default-config-backend.cpp
When config_file is already a basename and doesn't contain a slash, the
return value of find_last_of is std::string::npos which is out of
bounds.
=> default-config-backend: Fix out of range error

src/view/view.cpp
This is the reverse of what happens later in the function (L842):
```
if (!fullscreen && !this->tiled_edges) ...
```
=> view: Set geo to expanded wm geo on undecorate

src/core/core-impl.hpp
compiling with link-time optimizations turned on generated One
Definition Rule violation warnings due to input_method_relay being
referred to in the global namespace and being defined in wf::
This line was probably placed outside of wf:: by mistake.
=> core-impl: Fix ODR violation warnings with b_lto

metadata/expo.xml, plugins/common/wayfire/plugins/common/key-repeat.hpp, plugins/common/wayfire/plugins/common/workspace-wall.hpp, plugins/scale/scale-title-filter.cpp, plugins/single_plugins/expo.cpp
Fixes #1142
Arrows keys can be used to select a target workspace, enter to change, esc to cancel.
Also added shading to unselected workspaces.
TODO:
=> Expo: add keyboard interaction

.github/workflows/ci.yaml, metadata/workarounds.xml, src/core/output-layout.cpp
Currently, if an external application like kanshi sets the output configuration, Wayfire will reset it to the values in the config file whenever the config file is reloaded.
To fix this, the new `workarounds/use_external_output_config` option modifies Wayfire's handling of output configuration: when this option is true, Wayfire will ignore any values in the config file (except mirroring) and use the values given by kanshi (or any similar program).
=> output-layout: add workarounds/use_external_output_config

src/api/wayfire/opengl.hpp, src/core/opengl.cpp, src/core/seat/seat.cpp, src/output/workspace-impl.cpp, src/util.cpp, src/view/surface-impl.hpp, src/view/surface.cpp, src/view/view-impl.hpp, src/view/view.cpp
- seat: set current keyboard
- opengl: use unordered_map for accessing uniforms
- opengl: add cached drawing support
- opengl: disable gl_call for internal commands
- view: reserve space for enumerate_views() vector
- surface: reserve space for enumerate_surfaces() vector
- util: optimize geometry intersection
- workspace-impl: add a flat view list
More or less fixes #752
My tests however don't show a big improvement in real-life usages. Maybe we're already as fast as we can be :)
=> cpu micro-optimizations

src/api/wayfire/surface.hpp, src/view/subsurface.cpp, src/view/surface.cpp, src/view/view.cpp
As discussed here:
https://github.com/Javyre/swayfire/pull/24#issuecomment-854393828
This isn't too useful yet as the subsurfaces still get dropped on `set_decoration()`. I feel like `set_decoration()` should either not `remove_subsurface` at all or at least return the pointer as well. (although that would be messier since there's less guarantee you're getting back your own surface form the `set_decoration(nullptr)`)
=> surface: Return owned surface on remove_subsurface

plugins/common/wayfire/plugins/common/move-drag-interface.hpp, plugins/single_plugins/move.cpp
Fixes #1186 (only the case with the move plugin)
Tested with regular move, drag with expo active and setting `workarounds/all_dialogs_modal` both on and off. Did not test with multiple outputs. Does not work if `move/join_views = true`, in that case, it seems that the clicked view is "forgotten" when the drag starts.
=> Focus the main dragged view when a drag ends

src/core/output-layout.cpp
`ensure_noop_output` truly is an "ensure" function, not a "create" one. Among other things, it cancels the `timer_remove_noop`, which always needs to be done.
Otherwise, rapid changes in output configuration (that do happen for me currently with turning my monitor back on after turning it off) cause a situation where the `timer_remove_noop` fires right after removing the last output, causing the noop to be removed too, which results in a crash.
=> output-layout: do not check for noop's existence when ensuring it exists

plugins/decor/deco-subsurface.cpp, src/api/wayfire/plugin.hpp, src/api/wayfire/view.hpp, src/view/view-impl.cpp, src/view/view-impl.hpp, src/view/view.cpp
This doesn't work yet as I'm still working on it.
I'm not sure how you want to split the deco plugin's `simple_decoration_surface`. Do you want to store the surface state in the surface itself or in the decoration frame? The new `simple_decoration_frame` could also just be empty and forward all the events to the surface.. I'm not sure how you want to approach this.
=> WIP: deco: Separate decoration surface from frame.

metadata/vswitch.xml, plugins/scale/scale.cpp, plugins/vswitch/vswitch.cpp, plugins/vswitch/wayfire/plugins/vswitch.hpp
There is also support for directly moving a view to a workspace.
Vswitch now supports the following options:
`binding_{N, dir}` -> Move to workspace N or in the given direction
`with_win_{N, dir}` -> Move to workspace N or in the given direction together with focused window.
`send_win_{N, dir}` -> Move focused window to workspace N or in the given direction.
`N` is the workspace number, workspaces are numbered from left to right, top to bottom.
`dir` can be `left`, `right`, `up` or `down`.
Important: this contains a breaking change for vswitch. `binding_win_left/etc` were renamed to `with_win_left/etc`, to avoid conflicts between option lists, otherwise `binding_win_1` could be interpreted either as 'move with window to workspace 1' or 'move to workspace `win_1`'
=> vswitch: add support for motion to absolute workspace pos

.github/workflows/ci.yaml, meson.build, meson_options.txt, src/api/wayfire/geometry.hpp, src/api/wayfire/plugin.hpp, src/core/core.cpp, src/main.cpp, src/meson.build, src/util.cpp, test/geometry/geometry_test.cpp, test/geometry/meson.build, test/meson.build
This PR adds basic infrastructure for unit tests with doctest.
Since Wayfire's design does not rely too heavily on interfaces, we can hardly isolate different parts of the code from each other.
As a result, most of Wayfire's code needs to be compiled into a static library, which is then compiled with `main.cpp` to produce the executable.
The same static library is also linked to the tests.
Currently, there is only a single very simple test case, it is more a proof-of-concept.
The upcoming transactions will be the first part of Wayfire itself which should be properly unit-tested, as should ideally be
any new big change in core.
=> unit test infrastructure

src/output/render-manager.cpp
This is most consistent with hardware cursor plane behavior.
Without this, there are bugs such as #1218.
=> render-manager: Render software cursors last

src/output/workspace-impl.cpp
It doesn't make sense for views to be added to a workspace without also
being on that output.
I think we should also assert that `damage()` isn't being called when `!get_output()`, but I don't know exactly where best to assert this...
=> workspace-impl: Ensure output is set on add_view_*

src/api/wayfire/nonstd/wlroots.hpp
Change wlr/types/wlr_types.h to wlr/utils/box.h fix the build warnings.
=> wlr/types/wlr_types.h -> wlr/utils/box.h

meson.build
dlclose POSIX docs say "Although a dlclose() operation is not required
to remove structures from an address space, neither is an implementation
prohibited from doing so."[1]. The fno-gnu-unique option makes it so the
plugin is unloaded when dlclose is called[2]. This makes wayfire use less
resident memory when unloading plugins. It also allows developers to make
changes to wayfire plugins without restarting wayfire.
1. The Open Group Base Specifications Issue 6.
http://pubs.opengroup.org/onlinepubs/007904975/functions/dlclose.html
2. GCC Code Gen Options.
https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html
=> build: Add -fno-gnu-unique compiler option

src/api/wayfire/output.hpp, src/output/output-impl.hpp, src/output/output.cpp, src/output/workspace-impl.cpp
Preserve last-focused order on workspace changed.
This is an alternative, simpler solution for the issue described in #1237. The solution is to simply not meddle with the focus timestamps on `set_workspace()`.
This should also cover the cases described in the previous attempt where if a view is sticky or spans multiple workspaces it could lead to unintuitive behaviour.
=> output: preserve last-focused order (take 2)

metadata/animate.xml, plugins/animate/fire/fire.cpp
This PR adds 2 settings, `fire_color` (color) and `random_fire_color` (boolean).
If `random_fire_color` is false, the fire will be colored according to `fire_color`. If it is true then the color of each particle will be randomized.
=> Add settings to fire effects

plugins/scale/scale.cpp, plugins/single_plugins/switcher.cpp
Both the Scale and Switcher plugins have a bug that can leave the wrong view focused by the pointer after using them. This means that scrolling the mouse wheel after selecting a view with these plugins can scroll the wrong view.
This fixes emits an `output-stack-order-changed` signal at the end of both of these plugins' animation when closing them, to cause `update_cursor_focus` in `src/core/seat/pointer.cpp` to recalculate which view should have focus.
Fixes #1280
=> Scale focus bug

src/view/surface.cpp
Surface parent_link and subsurface lists moved to state.
Required due to these wlroots commits:
https://github.com/swaywm/wlroots/commit/3ac99fa4dcbfcaf12e4e714529fd6b6eb03fd9fb
https://github.com/swaywm/wlroots/commit/90e62390d94dcdf2810e2fd60df505449e4d5917
=> Fix for wlroots change

metadata/wm-actions.xml, plugins/wm-actions/wm-actions.cpp
For feature request #1269 
I also noticed a missing binding removal in fini(), so I added it in a separate commit.
=> WM-Actions Send to back functionality

src/api/wayfire/plugin.hpp, src/api/wayfire/view.hpp, src/view/view.cpp
Code refactoring to merge `void take_snapshot()` with `const wf::framebuffer_t get_snapshot()` int one function: `const wf::framebuffer_t take_snapshot()`. It's basically the `take_snapshot()` function which also returns the captured buffer.
=> merging get_snapshot() with take_snapshot()

meson.build, src/output/plugin-loader.cpp
This came up twice in conversation on IRC and it's quite verbose to
track it down from scratch every time.
I think it would be useful to have this in the code to easily find and
point at.
=> plugin-loader: clarify dlclose() behaviour

metadata/core.xml
Wayfire crashed if vwidth or vheight was set to <= 0. Set the minimum
vwidth and vheight to 1, so we always have at least one workspace.
Fixes #1290.
=> core: Set minimum workspaces to one

wayfire.ini
When trying to set wayfire up, I noticed that the placeholder config has a "layout" field (that seemingly does nothing) instead of "position"
=> Rename output.layout field in example config to output.position

src/core/output-layout.cpp
We depended on wlroots rendering functions which have had breaking changes. Use our own functions instead.
Fixes #1336
=> output-layout: fix mirroring

src/view/layer-shell.cpp
configure_serial changes every time, so programs like slurp and swaylock
would enter a loop.
Fixes #1328
=> manually compare wlr_layer_surface_v1_state

src/api/wayfire/core.hpp, src/api/wayfire/output.hpp
Randomly came accross this while making bindings for wflua. IIUC, this wording should be equivalent.
=> output: minor wording simplification.

src/core/core.cpp
Otherwise an extra file descriptor for /dev/null will leak into
applications launched by Wayfire. In my case, it was fd 58.
=> core: close dev_null before running command

plugins/common/wayfire/plugins/common/move-drag-interface.hpp, plugins/scale/scale.cpp
Before, any movement between click and release would reset 
last_selected_view, resulting in BTN_LEFT not ending scale.
Now this only happens after the drag snap-off is triggered, making it
less likely to happen accidentally.
=> scale: allow small mouse movement between click and release

plugins/scale/scale.cpp, src/api/wayfire/compositor-view.hpp, src/api/wayfire/view.hpp, src/core/core.cpp, src/core/seat/keyboard.cpp, src/core/seat/seat.cpp, src/core/wm.cpp, src/output/output.cpp, src/view/compositor-view.cpp, src/view/view-impl.cpp, src/view/view-impl.hpp
Instead, we use a new unified interface for passing keyboard focus and key events to views, which can be used for both the wlroots and compositor path.
=> api: remove compositor_view_t

src/view/surface.cpp
Currently wayfire scales windows with default GL_LINEAR method. When scaling up this method gives blurry edges. For integral scales GL_NEAREST will give shape lines and blocky text instead, which looks much nicer. See files attached in [this comment](https://github.com/swaywm/wlroots/issues/1770#issuecomment-515404622).
Sway has [already supported this](https://github.com/swaywm/sway/pull/4727). It defaults to GL_NEAREST and has an option to change.
This patch makes wayfire to use GL_NEAREST when scale is an integer but I don't know how to make it an option.
I have [a better solution for xwayland windows on HiDPI monitors](https://gitlab.freedesktop.org/lilydjwg/wlroots/-/tree/hidpi) but it depends on [an xwayland patch which has stalled for some …
=> use GL_NEAREST for integer scale

plugins/common/wayfire/plugins/common/preview-indication.hpp, plugins/decor/deco-subsurface.cpp, plugins/grid/wayfire/plugins/crossfade.hpp, src/api/wayfire/compositor-view.hpp, src/api/wayfire/core.hpp, src/api/wayfire/view.hpp, src/core/core.cpp, src/core/seat/input-manager.cpp, src/core/seat/pointer.cpp, src/core/seat/seat.cpp, src/core/seat/seat.hpp, src/core/seat/tablet.cpp, src/output/gtk-shell.cpp, src/output/render-manager.cpp, src/view/compositor-view.cpp, src/view/layer-shell.cpp, src/view/subsurface.cpp, src/view/subsurface.hpp, src/view/surface-impl.hpp, src/view/surface.cpp, src/view/view-impl.cpp, src/view/view-impl.hpp, src/view/view.cpp, src/view/xdg-shell.cpp, src/view/xdg-shell.hpp, src/view/xwayland.cpp
Instead of making `view_interface_t` a subclass of `surface_interface_t`, we use composition. Now each view has a main surface accessible via `get_main_surface()`.
This allows for cleaner separation of responsibilities, and we don't have to use hacks in `wlr_surface_base_t` to avoid double inheritance.
Also, this is a second step to supporting the same window being visible on multiple outputs, as we use shared pointers for surfaces.
Now, we can have multiple views which use the same surfaces.
This is of course also useful for plugins which need to override the way Wayfire handles surfaces - for example, by providing a custom Xwayland view implementation, but reusing the `wlr_surface` handling.
Another potential example are client-rendered server side decorations, or implementations of …
=> api: split views and surfaces

metadata/vswitch.xml, plugins/vswitch/wayfire/plugins/vswitch.hpp
Extend the vswitch plugin with bindings that allow switching back to the
last active workspace. The functionality is achieved by always
remembering the switching direction at each switch, so that we can
easily reverse it. There in now not only a binding for switching to the *last*
workspace, but also two other bindings: 1) for taking the current view
with when switching and 2) for only sending the currently focused view
to the *last* workspace.
Fixes #1296
=> Implement switch to last workspace feature for vswitch plugin

plugins/single_plugins/preserve-output.cpp, src/api/wayfire/nonstd/wlroots-full.hpp, src/core/output-layout.cpp, src/core/seat/touch.hpp, src/core/wm.cpp, src/core/wm.hpp, src/output/render-manager.cpp
- output-layout: save output buffer ourselves on commit
It is used for mirroring later.
- output-layout: use headless instead of noop backend
First step towards #1386
=> update wlroots version to 0.15.0

.github/workflows/ci.yaml, meson.build, src/api/wayfire/nonstd/wlroots-full.hpp, src/core/core.cpp
As discussed previously on IRC, Wayfire-git will no longer follow wlroots-git.
Instead, Wayfire will always depend on a particular wlroots release.
This should make it easier to build Wayfire-git, since the current situation is that Wayfire  lags behind wlroots-git most of the time.
=> use wlroots stable

meson_options.txt, plugins/ipc/ipc.cpp, plugins/ipc/ipc.hpp, plugins/ipc/meson.build, plugins/ipc/stipc.cpp, plugins/meson.build, subprojects/json.wrap
This PR adds a simple IPC mechanism to Wayfire.
The purpose of this PR and all features it will ever implement are the bare minimum needed for automatic Wayfire tests. I have started working on some [tests](https://github.com/ammen99/wayfire-tests), however, the tests are quite opinionated and incomplete, so they are not included in the Wayfire organization yet.
Obviously, some users will (ab)use this IPC mechanism, especially as it will get more powerful features like querying workspaces. However, I do not recommend this, as this IPC **is not meant for users**, but for automatic tests. As a consequence, no features to the `stipc.cpp` plugin will be accepted which are not useful for the automatic tests.
The plugin is meant to be kept at the bare minimum necessary for the tests, as the …
=> Add debug IPC

plugins/ipc/meson.build
It makes no sense to install the json subproject if nlohmann/json is available system-wide.
=> stipc: use system nlohmann/json if available

plugins/single_plugins/expo.cpp
Something found while working on a #1381 related plugin. I wonder how nobody found this when working on tile :)
re: code style — I think skipping over `update_target_workspace(to.x, to.y);` with the `return` is fine, and the whole `if (view)` thing could've been ` if (!view) return;` to save an indent level, right?…
=> expo: ask the workspace_implementation about moveability

plugins/ipc/stipc.cpp
Otherwise, some clients like Xwayland do not process events immediately
and wait for a frame event, which never comes.
=> stipc: send pointer frame events

plugins/ipc/stipc.cpp
If plugin is loaded from the very beginning, then the backend will be
started twice - once from stipc, once when the multi-backend starts.
=> stipc: start multi backend only if running

plugins/ipc/stipc.cpp
For example, pointer-constraints can't be tested with absolute pointer events because core does not implement that.
=> stipc: send relative pointer events to emulate real workloads better

.github/workflows/ci.yaml, src/api/wayfire/signal-provider.hpp, src/core/object.cpp, src/debug.cpp
@Javyre thoughts ?
Eventually, this should fix #1307 
If anybody is interested in why I want to do this change, some of the rationale is described here: https://github.com/WayfireWM/wayfire/commit/22741481159b28a7c7204c87d3d3530b85902e83
Also, this new implementation can be improved even further to use static storage for different signals (thus eliminating the unordered_map lookup), also we can use a simpler `safe_vector_t`-like type to make iteration cache-efficient and lower the overhead of signals even further, if need be. Currently, signals are not that critical for performance and I have opted for a simpler (and a bit slower) implementation.
=> Make signal API identify signals by their signal data and not arbitrary strings

plugins/ipc/stipc.cpp, plugins/single_plugins/expo.cpp, src/main.cpp
- stipc: add touch
- stipc: make the key simulation command more flexible
- expo: grab views at the grab origin point, not after the motion
- main: allow starting headless backend only
- stipc: enable the removal of wayland outputs
=> Misc fixes for automatic tests

.github/workflows/ci.yaml, src/debug-func.hpp
Otherwise, the CI breaks, as Alpine does not have execinfo anymore. If not present, we cannot generate a backtrace, so we just print that.
=> debug: enable compilation without execinfo.h

plugins/single_plugins/idle.cpp, src/api/wayfire/workspace-manager.hpp
The function was removed, which broke idle. Fix idle by counting fullscreen views manually instead of using get_promoted_views() and remove the function from the header.
=> Remove get_promoted_views() from header

plugins/tile/tree-controller.cpp
=> simple-tile: fix use-after-move error in preview implementations

src/view/view-impl.cpp, src/view/view-impl.hpp
I'm closing the [older PR](https://github.com/WayfireWM/wayfire/pull/1557) in favor of this. There is no difference between that and this, except for the uncrustify.
=> Feat: Implement wlr_foregin_toplevel_handle's fullscreen management

src/core/seat/tablet.cpp
Fixes issue #1415, which is a crash when plugging in a graphics tablet, by adding a null check. It appears to be necessary to have a window open and XWayland running to trigger the bug.
I developed this against `v0.7.2` but rebased to `master` for this pull request. I can switch to another branch as well - I'm a bit new to this whole open-source thing, so I'm not sure what's best to do.
=> core: fix crash when connecting graphics tablet

plugins/vswitch/wayfire/plugins/vswitch.hpp
This PR fixes a small annoyance with the `binding_last` functionality of `vswitch` (thanks for this btw :-))
Basically, if I'm in e.g. workspace 1, go to workspace 2, then go again to workspace 2 (by pressing the key for `binding_2`), `last_dir` becomes 2, and essentially "forgets" 1.
With this PR `last_dir` is only set when `target_ws` differs from `ws`.
=> vswitch: check target_ws and ws before setting last_dir

metadata/input.xml, src/core/seat/pointing-device.hpp, src/core/seat/tablet.cpp
> Fixes the issue about motion of graphical tablets opened from me a while ago: https://github.com/WayfireWM/wayfire/issues/1137
> I'm not an C++ developer and also do not really know how the wayfire internals work but I made this changes for myself and they seem to work. So maybe they can be merged with a couple of adjustments here and there.
New pull request to target master. Original has been #1414.
=> Add tablet motion options

metadata/window-rules.xml
Currently, window-rules does not have any option. Therefore, it's difficult for the parser to auto-magically load the stored rules. Furthermore, since it does not have any option defined, wcm also does not list the rules, or allow it's modification. This MR adds the "rules" option of type "dynamic-list" to window-rules.xml file.
=> Add an option "rules" to window-rules with type "dynamic-list"

metadata/workarounds.xml, plugins/blur/blur.cpp, plugins/single_plugins/move.cpp, plugins/tile/tile-plugin.cpp, src/api/wayfire/debug.hpp, src/api/wayfire/output.hpp, src/api/wayfire/scene-input.hpp, src/api/wayfire/scene-render.hpp, src/api/wayfire/scene.hpp, src/api/wayfire/surface.hpp, src/api/wayfire/view.hpp, src/core/scene.cpp, src/core/seat/drag-icon.cpp, src/main.cpp, src/output/output-impl.hpp, src/output/output.cpp, src/output/render-manager.cpp, src/output/workspace-impl.cpp, src/view/surface-node.cpp, src/view/surface-pointer-interaction.cpp, src/view/surface-root-node.cpp, src/view/view-keyboard-interaction.cpp, src/view/view-node.cpp
The direct scanout was implemented in an suboptimal way: the output was listing all views and using their properties to figure out which can be scanned out.
From a design perspective, this is quite bad because the output needs to know the internals of views.
This series of commits simplify the scenegraph structure a bit and make direct scanout a scenegraph operation.
This way, nodes themselves are free to choose whether and how to support scanout.
In addition, the workarounds/remove_output_limits option has been added. This allows an experimental mode where views may be visible on multiple outputs.
This, however, breaks some assumptions elsewhere in the code, so bugs are expected.
=> Scenegraph: make scanout a scenegraph operation

metadata/autostart.xml, metadata/command.xml, metadata/expo.xml, metadata/vswitch.xml, metadata/window-rules.xml
These changes are completely backward compatible with the existing ini backend.
Following additions have been made:
1. To each `option` node of `dynamic-list` type, `type-hint` attribute is added.
Options which are a simple list should specify `type-hint='plain'`. Example: autostart/autostart, window-rules/rules
Options which need one or more (key, value) pair, should specify `type-hint='dict'`. Example: command/bindings, vswitch/workspace_bindings
Options which take a list of strings should specify `type-hint='tuple'`. Potentially, session management.
2. To each 'entry' node of compound option, 'name' attribute is added.
This attribute is specifcally needed to store dict type options.
These attributes are needed save the config in hjson format such that it's intuitive to the user.
=> Enhancements to XML files for Hjson support

src/main.cpp, src/output/plugin-loader.cpp, src/output/plugin-loader.hpp
As an alternative to providing the full path, provide plugin name as the option's argument:
```
wayfire --config-backend hjson-config-backend
```
The current behaviour (which is providing the full path) is still valid.
```
wayfire --config-backend /usr/lib/wayfire/libdefault-config-backend.so
```
=> Take plugin name as --config-backend argument

plugins/single_plugins/switcher.cpp
=> switcher: disable minimized nodes correctly when exiting

plugins/wm-actions/wm-actions.cpp
Core changed get_views_in_layer() to take a minimized boolean in 31def7ee.
=> wm-actions: Fix show desktop restore

metadata/command.xml, plugins/single_plugins/command.cpp
Creates another type of command for the command plugin called release. On release of the binding the command will be called, instead of on press. This allows for things like Push to talk (unmute then mute) using a single button.
Tested by running this for weeks using it to trigger push to talk on Arch Linux.
=> Add release binding feature to core command plugin

metadata/idle.xml, plugins/single_plugins/idle.cpp
Patch to add an option to disable the idle plugin initially, only to be activated by the toggle shortcut.
As advocated in: #1653 
Fixes #1653
=> Implement idle plugin disable_initially setting

metadata/input.xml, src/core/seat/pointing-device.cpp, src/core/seat/pointing-device.hpp
Limited by the touchpad size, some dragging behavior may be hard to finish, eg selecting long texts. The libinput developers said that they are not going to implement the edge dragging[[1]](https://gitlab.freedesktop.org/libinput/libinput/-/issues/131), but there is another similar function called [drag lock](https://wayland.freedesktop.org/libinput/doc/latest/tapping.html#tapndrag), which is not yet implemented by wayfire.
PS. This is my first pr in github, so please let me know if I make something wrong. : )
Thanks.
=> input: add libinput drag lock.

src/api/wayfire/plugin.hpp
The API/ABI version should be bumped as there were many recent breaking changes.
=> plugin: bump api/abi version

plugins/scale/scale.cpp
The problem that this addresses can be reproduced with the following steps:
1. Have the `place` (with `mode = center`) and `scale` plugins
2. Open multiple windows with the same dimensions (e.g. terminals)
3. Start 'scale' mode
4. Focus a different window
5. Start 'scale' mode again
The position of the windows in the two scale activations should be different, which can make it difficult to keep track of which window is which.
This is because the sorting of the views is purely geometry based, and when the geometry is identical the order is essentially unspecified. 
While there is no ordering that makes more sense that the other, ensuring that the order is always the same (which we do by just comparing pointers) makes things more predictable.
=> scale: let views with the same geometry appear in the same order

src/core/seat/tablet.cpp
Straightforward backport of #1555 to the `0.7.x` branch. I'd appreciate if you could make a new release including this change, so that this change can hopefully make it into Debian bookworm.
=> Backport graphics tablet fix to 0.7.x

plugins/window-rules/window-rules.cpp
This fixes the [problem](https://github.com/WayfireWM/wayfire/pull/1607#issuecomment-1338902195) reported by @lilydjwg. Besides, it also makes window-rules work with hjson config backend.
=> Fix 'lazy' code of window rules

proto/meson.build
This is similar to how [swaylock](https://github.com/swaywm/swaylock/blob/ac3b49b6571ceda3f8db11a98bfe320106996280/meson.build#L34) finds the wayland-scanner binary. This gives better support for cross compilation.
=> use native binary for wayland-scanner

src/api/wayfire/core.hpp, src/core/core.cpp
Wayfire was advertising the protocol twice which breaks apps like waybar.
Fixes #1739.
=> foreign-toplevel: Cleanup remaining leftovers from moving to a plugin

src/view/wlr-surface-node.cpp
After removing a view from workspace-manager, wayfire was sending frame done events immediately on commit, if it was not visible on any output. In addition, we can check if the surface has a buffer to tell if it's mapped or not.
=> wlr-surface-node: Don't send frame events to surfaces with a buffer

src/default-config-backend.cpp
The man page states "IN_MODIFY - File was modified", which seems to make sense for monitoring the config file. However, some users have reported strange crashes during or after modifying the config file, apparently due to the file being partially written when it is read. The man page also shows "IN_CLOSE_WRITE - File opened for writing was closed". This sounds like a better fit and prevents the potential crashes. Fixes #1722.
=> default-config-backend: Use IN_CLOSE_WRITE instead of IN_MODIFY

plugins/tile/tile-plugin.cpp
After resizing a tiled window with the key binding `button_resize`, wayfire does not response to any input. To avoid this, We need to ungrab the input when deactivating the plugin.
I'm not sure if this is related to #1725, which seems to have a similar behavior.
In addition, the plugin never receives the  `WLR_BUTTON_RELEASED` event corresponding to the `WLR_BUTTON_PRESSED` event in the key binding. We have to mark the key binding as unhandled so that there's a record of the `WLR_BUTTON_PRESSED` event, then grab input with `retain_pressed_state` set to true.
I've also seen similar issue in `wrot`. I guess it could be fixed like this.
=> simple-tile: Fix no response to input after move/resize a tiled window.

src/api/wayfire/view-transform.hpp
This missing line was causing only the top left quadrant of surfaces to be rendered with scale = 2, for example. Fixes #1750.
=> Fix broken scale

plugins/blur/blur-base.cpp, plugins/blur/blur.cpp, plugins/blur/blur.hpp, plugins/blur/bokeh.cpp, plugins/blur/box.cpp, plugins/blur/gaussian.cpp, plugins/blur/kawase.cpp, plugins/scale/scale.cpp, plugins/single_plugins/switcher.cpp, plugins/tile/tile-plugin.cpp, plugins/wm-actions/wm-actions.cpp, src/api/wayfire/plugin.hpp, src/api/wayfire/signal-definitions.hpp, src/output/output-impl.hpp, src/output/output.cpp, src/output/workspace-impl.cpp, src/view/view.cpp
These signals are used in just a few plugins and do not reflect the way Wayfire's API should be used.
Namely, a view is no longer bound to a single layer on one output (since scenegraph), even though most views are, in practice.
Replacement: use view-mapped, view-unmapped, view-disappeared, view-set-output (which indicates the view's 'primary output'), depending on what the plugin needs to handle.
=> Remove attach and detach signals

ipc-scripts/inactive-alpha.py, ipc-scripts/ipc-rules-demo.py, ipc-scripts/wayfire_socket.py, plugins/grid/grid.cpp, plugins/grid/meson.build, plugins/grid/wayfire/plugins/grid.hpp, plugins/ipc/ipc-activator.hpp, plugins/ipc/ipc-method-repository.hpp, plugins/ipc/meson.build, plugins/single_plugins/alpha.cpp, plugins/single_plugins/ipc-rules.cpp, plugins/single_plugins/meson.build, plugins/single_plugins/move.cpp, plugins/window-rules/view-action-interface.cpp, plugins/wm-actions/meson.build, plugins/wm-actions/wm-actions.cpp, src/api/wayfire/signal-definitions.hpp, src/output/workarea.cpp
Window-rules are currently limited to whatever we implement in core, and use a weird custom syntax.
It is possible to move window-rules to an IPC script, as this PR demonstrates. The question is, do people prefer the old or the new approach? Let me know what you think.
Here are some of my arguments why the one or the other:
Pros of the old approach:
- The custom syntax window-rules lets us have the configuration in one file, `wayfire.ini`.
- The custom syntax rules are applied immediately, with IPC there is a slight delay until the changes are applied (a frame or two at most).
- You don't need to know Python or a similar language (but you have to learn quirky custom syntax ...)
Pros of the IPC approach:
- Different plugins can add different IPC commands, so we do not need window-rules to …
=> [RFC] Move window rules to IPC scripts

src/output/output.cpp
The signal more or less represents that.
Fixes #1680
=> output: emit focus-changed signal when active view is changed

plugins/single_plugins/preserve-output.cpp, plugins/single_plugins/wsets.cpp, src/core/output-layout.cpp
This PR changes the way the `preserve-output` plugin works, and is thus a breaking change for all users that use it.
The original intention of this plugin was to gracefully handle the case where a monitor reports itself as turned off while DPMS is active. Without `preserve-output`, Wayfire would move all windows off that monitor, causing a messed up state (windows lose their workspaces, positions, etc). The `preserve-output` plugin used to move the windows to a different output, and then to restore them when the idling monitor is reconnected.
With workspace sets, we have a much more powerful way of doing that, because we can simply detach the workspace set from a monitor before it is removed, and then restore it when the monitor is online again. That however means that the views from that …
=> [breaking] Rewrite preserve-output

plugins/protocols/gtk-shell.cpp
Checking for xdg-surface to make gtk4-layer-shell work and avoid crashes. See #1854
Fixes #1854
=> Check for xdg-surface in gtk-shell plugin

plugins/common/wayfire/plugins/common/input-grab.hpp
Resubmit of #1769 with the fix placed at the proper place.
Fixes #1756
=> Restore the cursor shape to default when activating scale or expo

metadata/resize.xml, plugins/single_plugins/resize.cpp
In some cases it's desirable to keep the width / height ratio even when the application doesn't require it, e.g. resizing scrcpy out of ratio will leave unpleasant black space.
The patch adds another key binding to resize to keep ratio.
=> resize: support for keeping ratio

src/core/window-manager.cpp
The request for native size should happen after all other requests, otherwise they will overwrite it.
Fixes #1879
=> window-manager: carefully order the request for native size

.github/workflows/ci.yaml, meson.build, plugins/blur/blur.hpp, plugins/cube/shaders.tpp, plugins/scale/scale.hpp, src/api/wayfire/view.hpp, src/meson.build, src/output/output-impl.hpp, src/pch/pch.h, src/view/view-keyboard-interaction.hpp
C++ is infamous for slow compile times when you (over)use templates like Wayfire does.
These changes enable:
- Precompiled headers for core, seems to speed up compilation quite a lot. For plugins, we cannot use pch because meson precompiles headers for each target, and each plugin is a separate target. Also, my experiments show that adding PCH manually to plugins is not super beneficial.
- Unity builds (pass `--unity on` to meson), which also helps.
=> Improvements related to compilation times

plugins/single_plugins/fast-switcher.cpp
Set selected view to activated to get focus decorations. This makes the currently selected view much easier to see (described in #1745).
Also I just had to remove that #define.
=> fast-switcher: Set activated on selected view

plugins/single_plugins/switcher.cpp
With this PR, the "next view" is shown as the "center view" as soon as the plugin is activated. This removes the need to press `Alt-Tab-Tab` to focus the "next view".
=> [Switcher Plugin]: Animate to show next view on trigger

plugins/single_plugins/expo.cpp
Following up on #1811 I've implemented the IPC based activator for the Expo plugin (based on the example with scale). I have tested activating it from another plugin and via IPC. So far, I haven't included the workspace_bindings, since I'm not sure if there is a good use-case for them (they are only active when expo is activated).
=> expo: add support for ipc triggering

plugins/protocols/gtk-shell.cpp, src/api/wayfire/plugin.hpp, src/api/wayfire/window-manager.hpp, src/core/window-manager.cpp, src/view/xwayland/xwayland-toplevel-view.hpp
The code in xwayland and gtk-shell actually would not carry the request out!
Let's just use focus_request (which now has an argument for the self flag) rather than duplicating the carrying-out code.
=> view: use focus_request for self-requests from xwayland and gtk-shell

src/view/toplevel-view.cpp
See the discussion in #1274 
I did some quick testing and a search for where this signal is used, but let me know if I could do some more tests for regressions.
=> Do not send a view-disappeared signal when a minimized view is restored

plugins/common/wayfire/plugins/common/move-drag-interface.hpp, plugins/grid/wayfire/plugins/crossfade.hpp, plugins/scale/scale.cpp, plugins/single_plugins/fast-switcher.cpp, plugins/single_plugins/wrot.cpp, plugins/wobbly/wobbly.cpp, src/api/wayfire/plugin.hpp, src/api/wayfire/unstable/wlr-surface-node.hpp, src/api/wayfire/view-transform.hpp, src/api/wayfire/view.hpp, src/view/view-3d.cpp, src/view/view.cpp, src/view/wlr-surface-node.cpp, src/view/xdg-shell/xdg-toplevel.cpp, src/view/xwayland/xwayland-toplevel.cpp
When we have a pending transaction, we want to make sure we send a frame done to the client, so that it can resize. However, if it is already visible on an output, we should not send additional frame done events. Instead, we should wait until the 'normal' frame done events are sent as part of the rendering loop.
=> Visibility & surface frame done improvements

metadata/scale.xml, plugins/scale/scale.cpp
This can be helpful if scale is used as a primary method to switch between views. Of course, this is probably highly opinion-based, so I made this into a config option. Depends on #1906 
Issues / questions:
- ~~[ ] Option for an other plugin starting scale to specify whether to include minimized views (e.g. the dbus plugin [here](https://github.com/damianatorrpm/wayfire-plugin_dbus_interface/blob/c705bf1e9dbe54b7ecc3608869db7c53e82bb38d/dbus_interface_backend.cpp#L1095))~~
- ~~[ ] This currently works by setting the state of the view unminimized for the duration of scale; this is the easiest option to make it show up without extra hacks. Still, it could be an issue whether it is "logically" minimized or not (e.g. if a taskbar is displaying minimized views separately). Also, setting the …
=> Option to show minimized views in scale

plugins/ipc/ipc.cpp, src/api/wayfire/plugin.hpp, src/core/plugin-loader.cpp
This makes it less likely for the user to have problems with plugin ordering, especially since the IPC plugin should be first.
=> api: implement plugin ordering hints

src/api/wayfire/nonstd/wlroots.hpp
Suggested improvement for #1918 
This is the simplest possible solution that will leave WLR_USE_UNSTABLE defined -- if this is not desired, I could change this to conditionally undefine it after the wlroots includes (if it was not originally defined).
=> Always define WLR_USE_UNSTABLE

plugins/wm-actions/meson.build, plugins/wm-actions/wm-actions.cpp
Adding some more functionality in line with #1811
=> wm-actions: allow show desktop to be called from IPC (and other plugins)

meson.build
After 0.8.0, there comes the 0.9.0-git
=> bump meson.build to 0.9.0 (development version)

src/api/wayfire/nonstd/safe-list.hpp, test/misc/meson.build
Regressed by e2bf7b278d17. Found on FreeBSD [13.2](https://www.freebsd.org/security/#sup) (inside poudriere jail).
=> Unbreak build on FreeBSD

meson.build
We grab the commit hash and branch name for use in the log, but this does not work when building from a tarball. Tell meson to ignore the return value by setting 'check: false' for git commands.
=> build: Tell meson to ignore the return value of git commands

src/core/output-layout.cpp
Fixes #1408
Tested on both Intel and AMD iGPUs.
=> output-layout: use wlr_texture_from_buffer directly

src/view/xdg-shell.cpp, src/view/xdg-shell.hpp
This implements [xdg-shell v3](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3514). GTK 4 can use the reposition functionality to move its popups, which avoids flickering by the fallback way to hide and show popups.
This is especially useful since Wayfire doesn't fully implement the wayland input protocol and input methods resort to client side rendering.
(This patch is adapted from an earlier patch about which I don't remember many details, but it works.)
=> support reposition popups

metadata/command.xml, metadata/resize.xml, plugins/common/wayfire/plugins/common/workspace-wall.hpp, plugins/single_plugins/move.cpp, plugins/single_plugins/switcher.cpp, src/api/wayfire/opengl.hpp, src/api/wayfire/scene-input.hpp, src/api/wayfire/scene-render.hpp, src/api/wayfire/util.hpp, src/api/wayfire/view-transform.hpp, src/core/gldebug.hpp, src/core/opengl.cpp, src/core/wm.cpp, src/output/workspace-stream.cpp
Found by [typos](https://github.com/crate-ci/typos).
=> fix some typos

plugins/common/wayfire/plugins/common/util.hpp, src/api/wayfire/output.hpp, src/api/wayfire/plugin.hpp, src/output/output.cpp, src/output/workspace-stream.cpp
This function helps plugins to deal with always-on-top views.
Fixes #1953
=> api: add collect_output_nodes() and use this in plugins

wayfire.ini
This makes it clearer how to set the key to switch the keyboard layout, I think this should be included in the config because to use multiple layouts you need to set a way to switch between them. This was inspired by the discussion at #1326
=> Add `xkb_options` to `wayfire.ini`

src/core/output-layout.cpp
Fixes #1977
@Nosirus can you test this PR and confirm that it works for your machine too?
=> output-layout: add support for custom modes in wlr-output-management-v1

src/view/xdg-shell.cpp
Popups may receive keyboard input.
Fixes a regression in google-chrome in Wayland mode.
=> xdg-popup: set keyboard focus surface to not null

plugins/tile/tile-plugin.cpp
Otherwise, we only connect once the wset has been attached to another
output, which is too late.
Fixes #1983
=> simple-tile: connect to workarea changed when creating wset

metadata/workarounds.xml, src/core/core-impl.hpp, src/core/core.cpp
=> core: add an option to accept or discard command output

src/core/core.cpp
so that autostart commands pick it up.
I made a mistake in the last pr.
=> core: discard_command_output needs to be initialized before plugins

src/output/workspace-impl.cpp
Fixes #1991
The idea is that otherwise we can have race conditions depending on the
order of the output-configuration-changed handlers.
=> workspace-impl: return output size directly if output is attached

src/view/xwayland/xwayland-toplevel-view.hpp
We can't really give focus to the view anyway.
Fixes a bug which I'm not sure how to trigger in a test, but otherwise happens if I open a GLFW window which crashes before showing anything.
=> xwayland: do not honor request_activate() if the view is not mapped yet

plugins/single_plugins/ipc-rules.cpp
This is more useful because the other IPCs take IDs and not names.
For backwards compatibility, also include the output name in an "output-name" member.
=> ipc-rules: change output from name to ID.

src/core/plugin-loader.cpp
Duplicate plugins are now ignored.
Fixes #2036.
=> plugin-loader: Only load plugins once

plugins/cube/cube.cpp
Currently it looks like the framebuffers are allocated on activate but never released. This causes a substantial memory leak. Fix this by adding a destructor to cube_render_instance_t that releases them.
Fixes #2059
=> Fix memory leak when activating cube plugin

ipc-scripts/move-to-workspace.py, ipc-scripts/wayfire_socket.py
This fixes the list_views method and the move-to-workspace.py example script.
=> ipc-scripts: fix wrong command name

plugins/decor/decoration.cpp, src/view/view-impl.cpp
Fixes https://github.com/timgott/wayfire-shadows/issues/19 and partially https://github.com/WayfireWM/wayfire/issues/2043
For the decoration plugin that should be very low overhead even if the maximized criterion is not used, so why not.
But please, can all view signals be consistently emitted on view, output and core at once.
=> Listen to tiled signal in deco plugin and emit view_tiled signal on core

metadata/oswitch.xml, plugins/single_plugins/oswitch.cpp
provide an api `wf::output_t *get_prev_output(wf::output_t *output)` in core/output-layout.hpp
and use this api to implement `prev_output` and `prev_output_with_win`
fixes #2071
=> add keybindings: prev_output, prev_output_with_win

metadata/output.xml, src/api/wayfire/output-layout.hpp, src/core/output-layout.cpp
Enable by setting [output:<NAME>] vrr = true, or using a client like wlr-randr.
Fixes #1009.
=> output: Implement adaptive sync option

.github/workflows/ci.yaml
Unfortunately, unity builds are not very well suited for the CI because they merge all files together. As a result, we may forget includes (like happened in #2053). Therefore, this PR disables unity builds in one of the two CI builds.
=> disable unity builds in one of the CIs

src/view/xdg-shell/xdg-toplevel-view.cpp, src/view/xwayland/xwayland-toplevel-view.hpp, src/view/xwayland/xwayland-unmanaged-view.hpp, src/view/xwayland/xwayland-view-base.cpp, src/view/xwayland/xwayland-view-base.hpp
The idea is that if the transaction is delayed, the surfaces and their textures may be destroyed. So, we need to emit the signal as soon as possible.
Fixes #2014
=> views: emit pre_unmap immediately when starting a transaction

src/api/wayfire/core.hpp, src/api/wayfire/nonstd/wlroots-full.hpp, src/api/wayfire/nonstd/wlroots.hpp, src/core/core-impl.hpp, src/core/core.cpp, src/core/output-layout.cpp
First time with C++ and wlroots, so not sure if everything here is exactly proper C++. This is based off of how swaywm handles DRM leasing. I'm running on Fedora Silverblue via my own image based off of Universal Blue, and I used SteamVR in an Arch Linux container via Distrobox. It seems to work fine with my HTC Vive, but I've only tested this for a few minutes. It should work fine with other native VR headsets, but I don't have any to test. It should also work fine with other VR runtimes such as Monado, but I haven't figured out how to set that up yet.
Fixes #1581
=> Support for wlr_drm_lease_v1

src/main.cpp
By default, writing to a pipe that has been closed terminates the program with SIGPIPE. Ignoring SIGPIPE results in the syscall failing with EPIPE instead.
This generally prevents crashing on IPCs. One crash I found is in write_selection_property_to_wl_client when using xpra to run remote apps. If xpra updates the selection too often, wayfire crashes with SIGPIPE. But this probably prevents other crashes in general. It also matches what other compositors do, e.g., sway also globally ignores SIGPIPE to prevent crashes caused by IPCs.
=> main: ignore SIGPIPE globally.

plugins/decor/deco-button.hpp, plugins/decor/deco-layout.cpp, plugins/decor/deco-subsurface.cpp, plugins/decor/deco-theme.cpp, plugins/decor/deco-theme.hpp, src/view/toplevel-view.cpp
=> decor: Don't put minimize buttons on child views

src/view/surface.cpp
Most applications add their subsurfaces above the parent, so we were blindly adding them to the front. This patch checks if the subsurface should be below, and adds it to the back in that case, or else adds it to the front.
Fixes #1206.
Fixes #1615.
=> Add subsurfaces to the back that are meant to be below the parent surface

metadata/blur.xml
The degrade setting was too high, causing problems especially when moving a view around the screen.
=> Modify blur defaults to avoid visual artifacts

README.md
The URL link for `wayfire` Arch/AUR package collides with the URL link for `https://wayfire.org/` earlier in the document
=> Fix `wayfire` AUR link

metadata/output.xml, src/api/wayfire/output-layout.hpp, src/core/output-layout.cpp
Currently supports 8 and 10 bpc.
Fixes #2103.
=> output: Add bit depth property

.github/workflows/ci.yaml, src/view/layer-shell/layer-shell.cpp
This effectively makes it so the view that had focus before interacting with wf-shell apps, is focused after interactivity is complete.
Fixes #2118.
=> layer-shell: Refocus the keyboard focus view after arranging layers

src/core/seat/keyboard.cpp
For these bindings we should still do a release because the press was registered.
Fixes #2064
=> keyboard: do not consume the release events from modifier bindings

plugins/ipc/demo-ipc.cpp, plugins/ipc/ipc-method-repository.hpp, plugins/ipc/ipc.cpp, plugins/ipc/ipc.hpp, plugins/ipc/meson.build, plugins/ipc/stipc.cpp, plugins/single_plugins/ipc-rules.cpp
This allows to fully replace the IPC socket with an alternative
implementation (dbus, json-rpc, whatever).
Fixes the remaining of #2120
=> ipc: make client interface really an interface

plugins/common/wayfire/plugins/common/workspace-wall.hpp
In Wayfire 0.7.2 we were using auxilliary buffers to composite the workspaces before finally drawing them on the screen.
In Wayfire 0.8.0 the behavior changed: all windows were directly composited on the screen. This introduced highly improved performance for cases where the workspace contents were changing, because we could render them at scale. However, it introduced problems with static workspaces containing multiple windows, because we'd have to composite
them multiple times on each frame.
The new implementation takes a best-of-both-worlds approach. We composite workspaces to auxilliary buffers, ensuring that we do not re-composite static surfaces together on each frame.
To ensure that dynamic content also works well, we scale the buffers as well, if enough of the content has changed …
=> optimize the GPU usage of workspace-wall

plugins/vswitch/wayfire/plugins/vswitch.hpp
I don't understand how the scenegraph APIs work, but by tinkering with the code it looks like adding the overlay as a child of the scene::output_node_t results in both the overlay and the original window being displayed, even though the original window is hidden with wf::scene::set_node_enabled on its transfomed node.
This fix works on one output, but if a window is split across multiple outputs, then the overlay appears on the wrong output as well. That said, windows split across multiple outputs don't seem to work at the moment - only one output displays its part of the window, the others don't - so I don't know if that's a problem with this commit or a deeper problem.
Fixes #2041
=> vswitch: remove "ghost window" on target workspace.

src/api/wayfire/signal-definitions.hpp, src/view/toplevel-view.cpp
The view is technically moved to a NULL wset.
=> toplevel-view: emit move_to_wset() when changing to a dialog

ipc-scripts/inactive-alpha.py, ipc-scripts/ipc-rules-demo.py, ipc-scripts/list-methods.py, ipc-scripts/wayfire_socket.py, meson.build, plugins/ipc/ipc-method-repository.hpp, plugins/single_plugins/ipc-rules.cpp, src/api/wayfire/debug.hpp, src/api/wayfire/signal-definitions.hpp, src/main.cpp, src/meson.build, src/version/git-branch.cpp.in, src/version/git-commit.cpp.in, src/view/view-impl.cpp
- ipc-rules: add ability to select which events to listen for
- view: emit title/app-id-changed on core as well
- ipc-rules: emit view-{title,app-id}-changed to subscribed clients
- meson: use vcs_tag for git version information
- ipc-rules: add wayfire/configuration method
=> ipc enhancements

plugins/single_plugins/ipc-rules.cpp
Haven't tested this yet, but this would be nice for laptop users plugging into different monitors.
=> ipc-rules: add output-added and output-removed signals

src/core/seat/input-method-relay.cpp, src/core/seat/input-method-relay.hpp, src/core/seat/keyboard.cpp, src/core/seat/keyboard.hpp, src/core/seat/seat-impl.hpp, src/core/seat/seat.cpp
This is continuation for #2111.
This is a draft as I haven't tested it for long. Also, it needs a fcitx5 patch (to not send superfluous release events).
=> Some input method fixes (take 2)

src/view/view-impl.cpp, src/view/xdg-shell.cpp
=> xdg-popup: include popup's own position in the calculation

src/core/seat/hotspot-manager.cpp
Otherwise, we may get NaN as its position from core, which causes subsequent problems.
Fixes #2176.
=> hotspots: verify that the touch event belongs to finger id 0

src/core/seat/input-method-relay.cpp
=> im-relay: fix text inputs created while a non-wlr node is focused

plugins/scale/scale.cpp
=> scale: fix moving view between different outputs

plugins/protocols/gtk-shell.cpp, src/api/wayfire/plugin.hpp, src/api/wayfire/signal-definitions.hpp, src/view/toplevel-view.cpp
Add wayfire_toplevel_view arg to two signals:
- view_activated_state_signal
- view_parent_changed_signal
=> Add views to signals

plugins/protocols/wayfire-shell.cpp, src/api/wayfire/unstable/wlr-text-input-v3-popup.hpp, src/core/core.cpp, src/core/output-layout.cpp, src/core/seat/input-method-popup.cpp, src/core/seat/tablet.cpp, src/view/layer-shell/layer-shell.cpp, src/view/view-impl.cpp, src/view/view-impl.hpp, src/view/xdg-shell.cpp, src/view/xdg-shell/xdg-toplevel-view.cpp, src/view/xwayland.cpp, src/view/xwayland/xwayland-view-base.cpp
We already changed the behavior similarly in #2123, so it should be fine to change it here too.
=> core: do not resize view in move_view_to_output

.github/workflows/ci.yaml, meson.build, meson_options.txt, plugins/animate/fire/fire.cpp, plugins/animate/fire/particle.cpp, plugins/animate/fire/particle.hpp, plugins/animate/meson.build
=> use OpenMP for simplifying thread setup in fire particle animations (master branch)

metadata/animate.xml, metadata/cube.xml, metadata/expo.xml, metadata/grid.xml, metadata/scale.xml, metadata/simple-tile.xml, metadata/switcher.xml, metadata/vswipe.xml, metadata/vswitch.xml, metadata/wsets.xml, metadata/zoom.xml, plugins/animate/animate.cpp, plugins/animate/animate.hpp, plugins/animate/basic_animations.hpp, plugins/animate/fire/fire.cpp, plugins/animate/fire/fire.hpp, plugins/animate/system_fade.hpp, plugins/cube/cube.hpp, plugins/grid/grid.cpp, plugins/grid/wayfire/plugins/crossfade.hpp, plugins/scale/scale.cpp, plugins/single_plugins/expo.cpp, plugins/single_plugins/switcher.cpp, plugins/single_plugins/vswipe.cpp, plugins/single_plugins/wsets.cpp, plugins/single_plugins/zoom.cpp, plugins/tile/tree.cpp, plugins/tile/tree.hpp, plugins/vswitch/wayfire/plugins/vswitch.hpp
This PR updates the plugins to use the new animation option type from wf-config.
Note that there are no breaking changes, because the old way to use animations (integer duration option) still works.
Plugins which want to be more configurable have to update their code to use the new option type (which is very simple in most cases).
In any case, this change makes it possible to be a bit more explicit in the config file, for example `200ms` or `2.5s`, both are accepted.
For backwards compatibility, the user can also just write a simple number, `200` as before, which is interpreted as `200ms`.
Also, the animation easing function is now configurable if one uses the full format. For example, `200ms linear` or `200ms circle`. The default easing function was and remains circle, but sometimes …
=> Use the new animation option type

plugins/animate/fire/fire.hpp, plugins/ipc/ipc-method-repository.hpp, src/api/wayfire/option-wrapper.hpp, src/api/wayfire/plugin.hpp, src/api/wayfire/unstable/wlr-text-input-v3-popup.hpp, src/core/seat/drag-icon.hpp, src/core/seat/hotspot-manager.hpp, src/debug.cpp
- option-wrapper: catch exceptions and print meaningful error messages
- fix compilation warnings from clang
Fixes #638
=> improve log on wfconfig error

src/api/wayfire/debug.hpp, src/api/wayfire/unstable/wlr-view-events.hpp, src/api/wayfire/unstable/xwl-toplevel-base.hpp
* Otherwise wayfire could use the config.h of an already installed wayfire installation and lead to confusing linking issues if the options differed (like installed wayfire has xwayland disabled and the new build has it enabled).
=> Copy config.h approach from wlroots-full.hpp to other public api headers

src/default-config-backend.cpp
See the linked issue for context.
This is a strange bug, and I honestly don't know why this fix works (or, rather, why the original code was buggy). I wrote some smaller test programs, and `operator==` generally *does* seem to work over a flexible array member. I may be missing something obvious, or there may be some UB going on when `->name` is inspected in the buffer returned from `read(2)`. In any case, this fix appears to work, though I'd like some external confirmation or refutation of that given how shaky it seems. Thanks!
Commit message below:
```
If the config file is a symlink, wayfire attempts to watch the parent directory so that, if replaced via a subsequent `ln -sf`, it'll still be notified. When notified, however, wayfire doesn't immediately reload the config file. Rather, …
```
=> conf: fix reloading on IN_CREATE

README.md, meson.build
DRM, GLES2, libinput and session are all expected to be present unconditionally in wlroots-full.hpp which is a part of the wayfire api
https://github.com/WayfireWM/wayfire/blob/master/src/api/wayfire/nonstd/wlroots-full.hpp
=> Explicitly check wlroots features and fail if required ones are missing

.github/workflows/ci.yaml
There is no reason to catch all the latest bugs in a CI ...
=> ci: use alpine:latest instead of alpine:edge

src/api/wayfire/plugin.hpp, src/api/wayfire/unstable/wlr-surface-node.hpp, src/view/wlr-surface-node.cpp
Tested with weston-transformed.
Fixes #1770
=> surface-node: add support for surface transform

metadata/scale.xml, plugins/scale/scale.cpp
I'll add a config option for this behavior before marking this PR as ready, but this seems to work well at the moment.
=> scale: auto-close scale when a new view opens

plugins/ipc/ipc.cpp
=> ipc: do not be strict about utf8 when encoding json data

plugins/single_plugins/ipc-rules.cpp
Alternative to #2262
@CharlieQLe @killown Please take a look and test.
=> ipc-rules: add mechanism to connect signals only when a subscriber is really there

metadata/workarounds.xml, src/api/wayfire/debug.hpp, src/api/wayfire/plugin.hpp, src/api/wayfire/scene.hpp, src/api/wayfire/unstable/translation-node.hpp, src/api/wayfire/unstable/wlr-subsurface-controller.hpp, src/api/wayfire/unstable/wlr-surface-controller.hpp, src/api/wayfire/unstable/wlr-surface-node.hpp, src/core/scene.cpp, src/main.cpp, src/output/render-manager.cpp, src/view/translation-node.cpp, src/view/view-impl.cpp, src/view/wlr-subsurface-controller.cpp, src/view/wlr-surface-controller.cpp, src/view/wlr-surface-node.cpp
This PR changes the ABI but there should be no plugin breaking changes, so a simple recompile should suffice.
Fixes #2264
Fixes #1272
Fixes #864 
This PR also potentially significantly improves CPU usage, for example in a Firefox+gfx.webrender, from 80% total CPU usage to around 15%.
=> Improvements to surface and node handling

metadata/input-method-v1.xml, plugins/protocols/input-method-v1.cpp, plugins/protocols/input-method-v1.hpp, plugins/protocols/meson.build, plugins/protocols/text-input-v1-v3.hpp, proto/meson.build
Fixes #1789
Tested briefly with `weston-editor` and google chrome, which needs `--enable-wayland-ime` on the command line to work.
If someone else needs this, please test :)
=> protocols: add support for text-input-v1

plugins/single_plugins/ipc-rules.cpp, plugins/tile/tile-plugin.cpp, src/api/wayfire/plugin.hpp, src/api/wayfire/toplevel.hpp, src/view/xdg-shell/xdg-toplevel.cpp, src/view/xdg-shell/xdg-toplevel.hpp, src/view/xwayland/xwayland-toplevel.cpp, src/view/xwayland/xwayland-toplevel.hpp
- toplevel-interface: add min/max size APIs
- simple-tile: do not tile views with min==max size
- ipc-rules: report min/max size for toplevels
Fixes #2243
=> api add min max size

plugins/animate/fire/fire.cpp, plugins/common/wayfire/plugins/common/move-drag-interface.hpp, plugins/common/wayfire/plugins/common/workspace-wall.hpp, plugins/cube/cube.cpp, plugins/decor/deco-subsurface.cpp, plugins/grid/wayfire/plugins/crossfade.hpp, plugins/ipc/stipc.cpp, plugins/scale/scale-title-overlay.cpp, plugins/single_plugins/switcher.cpp, plugins/tile/tile-plugin.cpp, plugins/tile/tree-controller.cpp, plugins/tile/tree-controller.hpp, plugins/vswitch/vswitch.cpp, plugins/wobbly/wobbly.c, plugins/wobbly/wobbly.cpp, src/api/wayfire/plugin.hpp, src/api/wayfire/scene-render.hpp, src/api/wayfire/scene.hpp, src/api/wayfire/unstable/translation-node.hpp, src/api/wayfire/view-transform.hpp, src/core/scene.cpp, src/core/seat/pointer.cpp, src/output/render-manager.cpp, src/view/toplevel-node.cpp, src/view/translation-node.cpp, src/view/view-3d.cpp, src/view/xdg-shell/xdg-toplevel-view.cpp, src/view/xwayland/xwayland-toplevel-view.hpp
- pointer: use a copy of buttons to be released
- vswitch: restore ipc grabbing with view
Fixes #2303
Fixes #2307 
Fixes #2308
=> fix more crashes

plugins/protocols/session-lock.cpp
This ensures the active window, if any, has focus after the the screen is unlocked.
Fixes #2280
=> session-lock: refocus after lock destroyed.

wayfire.ini
Quick PR to remove comment from waybar.ini that says wf-dock is started by autostart_wf_shell ([issue](https://github.com/WayfireWM/wayfire/issues/2327))
Fixes #2327
=> Remove comment that says wf-dock started with autostart_wf_shell

ipc-scripts/headless.py, plugins/scale/scale.cpp, plugins/single_plugins/move.cpp, plugins/tile/tree.cpp, plugins/wobbly/wobbly.cpp, src/api/wayfire/plugin.hpp, src/api/wayfire/view-transform.hpp, src/core/core.cpp, src/debug.cpp, src/meson.build, src/view/toplevel-view.cpp, src/view/view-3d.cpp
- ipc-scripts/headless: rewrite with proper python argparse
- scale: properly handle view lifetimes
- view-transform: use weak pointer to views
- debug: force a crash to print asan stacktrace in print_trace(false)
- wobbly: handle case where node outlives transformer
- move: handle race condition where move request comes after button is released
- bump wf-config to fix a race condition
Fixes #2295
Fixes #2297
=> another round of fuzz testing

src/view/wlr-surface-node.cpp
Qt 6.7.0+ requires this to correctly scale when fractional scale is not enabled.
A simple PyQt6 program to demostrate:
```py
#!/usr/bin/python3
import sys
from PyQt6 import QtWidgets, QtCore
def main():
QtWidgets.QApplication.setHighDpiScaleFactorRoundingPolicy(
QtCore.Qt.HighDpiScaleFactorRoundingPolicy.RoundPreferFloor)
app = QtWidgets.QApplication(sys.argv)
test = QtWidgets.QLabel("测试 Qt")
test.show()
sys.exit(app.exec())
if __name__ == '__main__':
main()
```
Setting `QT_SCALE_FACTOR_ROUNDING_POLICY=RoundPreferFloor` for Qt6 apps should also reproduce it but not tested. This happens with Telegram (with "presice High DPI scaling" disabled) + Qt6 6.7.0.
Fixes #2253
=> send preferred_buffer_scale event after entering an output

plugins/common/wayfire/plugins/common/move-drag-interface.hpp, plugins/tile/tree.cpp, src/core/opengl.cpp, src/core/txn/transaction-manager-impl.hpp, src/core/txn/transaction.cpp, test/txn/transaction-test.cpp
- opengl: clear uniforms and attribute locations in free_resources()
- move-drag-interface: fix rare crash where focused output becomes null
- simple-tile: do not do crossfade for views without an output
- transaction: handle case with timeout=0 and empty transactions
Fixes #2342
Fixes #2344
Fixes #2351
=> final fixes for 09

metadata/input.xml, src/core/seat/pointing-device.cpp, src/core/seat/pointing-device.hpp
Many mice support natural/reversed scrolling through libinput these days. This enables mouse natural scrolling throug a separate config option specifically for mice.
=> Provide "natural scrolling" option for mice.

src/api/wayfire/plugin.hpp, src/api/wayfire/seat.hpp, src/api/wayfire/signal-definitions.hpp, src/core/seat/seat-impl.hpp, src/core/seat/seat.cpp, src/view/xdg-shell.cpp, src/view/xdg-shell.hpp
This is useful for example when we want to close popups on actual
focus change (user alt-tabbed, clicked outside of the view, etc.) but
not for 'mundane' reasons like a refocus if the popup does not have a
grab.
Fixes #2381
Workaround for #2365
=> core: add a reason hint for keyboard focus change

src/api/wayfire/output-layout.hpp, src/api/wayfire/plugin.hpp, src/core/output-layout.cpp
=> output-layout: mark custom modes explicitly

src/view/view-impl.cpp, src/view/view-impl.hpp, src/view/xdg-shell/xdg-toplevel-view.cpp, src/view/xwayland/xwayland-toplevel-view.hpp
Depending on their state, we might want different things.
Fixes a regression introduced somewhere in the last commits.
Also, this makes xdg-toplevels not exceed the output size when they are created, which is already being done for Xwayland views.
We will have to consider whether this makes sense at all...
=> toplevel-views: be more careful when mapping views

src/view/xdg-shell/xdg-toplevel-view.cpp
This calls `wlr_server_decoration_manager_set_default_mode` again when the setting `core/preferred_decoration_mode` in `wayfire.ini` is updated during runtime.
I figured out why it didn't work before and tried to implement that, but couldn't do that with valid C++ syntax due to my lack of C++ knowledge, so @soreau made the patch with proper C++ syntax, which is why I added him as co-author to the commit.
I tested this PR and it works completely as expected. Only with this PR, you will notice a bug in GTK, which I submitted a MR for at https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/7475
=> Set default decoration mode when it is adjusted at runtime

plugins/grid/grid.cpp, plugins/grid/wayfire/plugins/grid.hpp, plugins/single_plugins/move.cpp
Before, dragging to an edge with move enabled and grid disabled would result in the indicator being drawn for the slot but always maximized. Fix this by emitting a signal that grid or another plugin can tell move the request is handled, so move can try gridding. In this implementation, we just hard code top to maximize if grid is disabled.
Fixes #2403.
=> move: Check if grid is enabled before activating edges on drag

metadata/workarounds.xml
This makes the long options appear in tooltips and adds a short field for the option name, in wcm.
=> workarounds: Clean up metadata

wayfire.desktop
For convenience of making units or autostart entries common for all wlroots compositors
=> Add wlroots to DesktopNames

metadata/extra-gestures.xml, plugins/single_plugins/extra-gestures.cpp, src/api/wayfire/core.hpp, src/api/wayfire/plugin.hpp, src/core/core-impl.hpp, src/core/core.cpp, src/core/seat/touch.cpp, src/core/seat/touch.hpp
This makes the hold action way more useful, and also fixes double/triple/etc tap gestures.
=> core: improve gesture and touch focus APIs

metadata/core.xml, src/core/wm.cpp
=> core: Make exit binding configurable

src/api/wayfire/nonstd/wlroots-full.hpp, src/core/core.cpp, src/main.cpp, src/main.hpp
This can be used to work around broken drivers that accelerate the desktop but not the wayland clients.
=> core: Add legacy wayland drm option

metadata/core.xml, wayfire.ini
Adding the `session-lock` plugin as a default one to the [wayfire.ini](https://github.com/WayfireWM/wayfire/blob/master/wayfire.ini) and the [core.xml](https://github.com/WayfireWM/wayfire/blob/master/metadata/core.xml) config.
Done as part of the #2360 discussion.
Built Wayfire with changes from this PR on a VM. Got successful locking results using both [swaylock](https://github.com/swaywm/swaylock) and [waylock](https://github.com/ifreund/waylock) tools.
Please, let me know if additional validation results are needed.
=> Enable session-lock plugin by default

src/output/render-manager.cpp
=> render-manager: do not crash if running nested (no wlr_session)

plugins/ipc/ipc.cpp
The solution proposed by @killown to make the socket path unique. I have tested this and confirm that it works.
=> Make socket path unique

plugins/protocols/input-method-v1.cpp, src/api/wayfire/plugin.hpp, src/api/wayfire/signal-definitions.hpp, src/api/wayfire/unstable/wlr-text-input-v3-popup.hpp, src/core/seat/input-method-popup.cpp, src/core/seat/input-method-relay.cpp
A text input `commit` may come with a `set_cursor_rectangle` request, and we need to update the input method popup to follow the text cursor on the client side.
Previously we run the update on popup surface commit, but events may come out of order, i.e. the input method draws a new surface buffer as soon as it commits the input string, and then the client window will take some time to process the committed string and figure out the new position of cursor.
=> Input method: update input method popup positions on text input commit

plugins/single_plugins/move.cpp
Without this, touch fingers are not set yet which causes a visual jump when attempting to move drag a window with touchscreen devices. Use post signal so that the fingers are properly detected and the correct coordinates are used in the first place.
Fixes #2505.
=> move: Use post input signal for touch move grabs

plugins/animate/animate.cpp, plugins/animate/animate.hpp, plugins/animate/basic_animations.hpp, plugins/animate/fire/fire.cpp, plugins/animate/fire/fire.hpp, plugins/animate/meson.build, plugins/animate/spin.hpp, plugins/animate/squeezimize.hpp, plugins/animate/unmapped-view-node.hpp, plugins/animate/zap.hpp
The API for it is installed in the `wayfire/plugins/animate/animate.hpp` header.
How it works:
1. The external plugin providing extra animations needs to implement the actual animation by deriving from (and implementing the methods of) the `animation_base_t` class:
```cpp
class animation_base_t
{
virtual void init(wayfire_view view, wf::animation_description_t duration, animation_type type)
{}
/**
* @return True if the animation should continue for at least one more frame.
*/
virtual bool step()
{
return false;
}
/**
* Reverse the animation direction (hiding -> showing, showing -> hiding)
*/
virtual void reverse()
{}
};
```
2. The plugin can register its animation type with the animate plugin by using the animation effects registry class:
```cpp
// Automatically fetches the global …
```
=> animate: allow 3rd party plugins to provide additional animations

wayfire.ini
added dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XAUTHORITY to [autostart]
I think most people are using GTK apps and this command is almost mandatory.
Commenting it out is fine.  As long as it is included in the file so people are aware of it.  Right now it's buried in the wiki tips & tricks. 
Including it here should help people get their install on track faster.
=> Wayfire.ini

src/view/layer-shell/layer-shell.cpp
Fixes #2450 
This change avoids automatically focusing layer-shell surfaces when their keyboard interactivity is changed to ON_DEMAND. As discussed in https://github.com/WayfireWM/wayfire/issues/2422#issuecomment-2308661898, this is not intended. However, this change can lead to unexpected changes if an app expects that this will grab focus. So it might not be the best solution after all.
Main change: Layer-shell views can now intentionally lose focus by setting keyboard interactivity to NONE and then back to ON_DEMAND (thus allowing them to be later refocused by normal user interactions; this was not possible before).
Possible drawback: if an app sets keyboard interactivity to ON_DEMAND as a response to user action (e.g. mouse click), it will not get keyboard focus until further user …
=> layer-shell: do not grab focus if keyboard interactivity is set to ON_DEMAND

plugins/protocols/foreign-toplevel.cpp
This fixes a potential crash with compositor views when workarounds option app-id-mode is set to 'full'. The crash can be caused when attempting to use magnifier, with this option set.
=> foreign-toplevel: Fix potential crash when app-id mode is 'full'

src/api/wayfire/nonstd/observer_ptr.h
Found this while looking into the packaging status in Debian:
https://udd.debian.org/lintian/?packages=wayfire
There was one non-UTF-8 character in comments ('§'); instead of using the UTF-8 variant, I suggest to rephrase to use only ASCII characters for simplicity.
=> nonstd: fix source file encoding

src/main.cpp
To run wayfire as root, pass the option --with-great-power-comes-great-responsibility.
Fixes #2540.
=> core: Add option to run as root

src/api/wayfire/nonstd/wlroots.hpp, src/main.cpp, src/view/xdg-shell/xdg-toplevel-view.cpp
- xdg-toplevel-view: read csd state as soon as possible
- main.cpp: prepare wayfire for software rendering coming in wlroots 0.19
@soreau Please review, esp. the second commit.
=> Small fixes

metadata/workarounds.xml, src/output/render-manager.cpp
The force frame sync option causes glFinish() to be called after rendering but before commiting the new buffer. This can be used to workaround driver bugs, especially where dma-fences are not available for frame synchronization. This is the case with multi- threaded llvmpipe rendering, using drm or wayland backends.
=> workarounds: Add force frame sync option

src/core/plugin-loader.cpp
This changes a message like:
[wayfire.git/src/core/plugin-loader.cpp:87] error loading plugin: /usr/lib/libcwd_r.so.9: undefined symbol: elf_nextscn
into:
[wayfire.git/src/core/plugin-loader.cpp:87] error loading plugin [/usr/lib/wayfire/libpixdecor.so]: /usr/lib/libcwd_r.so.9: undefined symbol: elf_nextscn
In other words, not just print the dlerror, but print which plugin failed to load.
=> Add to log message which plugin failed to load.

src/debug.cpp
Fix fixes the compile warning,
../../../../github/wayfire/wayfire.git/src/debug.cpp: In function ‘std::string read_output(std::string)’: ../../../../github/wayfire/wayfire.git/src/debug.cpp:95:10: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
95 |     fgets(buffer, MAX_FUNCTION_NAME, file);
|     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In this case there is a potential problem: if gets returns NULL, then nothing was read and the buffer is uninitialized. Not only would this function be returning uninitialized data, an arbitrary amount of memory could be allocated into `line` (and be returned) when `std::string line = buffer;` is searching for a terminating zero in the uninitialized buffer.
I kinda rewrote …
=> Fix compile warning.

plugins/single_plugins/resize.cpp
This is needed so decorators render correctly in these cases.
=> resize: Respect client minimum and maximum sizes

plugins/ipc/ipc-method-repository.hpp, plugins/ipc/ipc.cpp, plugins/ipc/ipc.hpp, plugins/ipc/stipc.cpp, plugins/single_plugins/command.cpp, src/core/core-impl.hpp, src/core/core.cpp
This patch address the compiler warnings:
[455/476] Compiling C++ object src/liblibwayfire.a.p/core_core.cpp.o ../../../../github/wayfire/wayfire.git/src/core/core.cpp: In member function ‘virtual pid_t wf::compositor_core_impl_t::run(std::string)’: ../../../../github/wayfire/wayfire.git/src/core/core.cpp:433:10: warning: ignoring return value of ‘int pipe2(int*, int)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
433 |     pipe2(pipe_fd, O_CLOEXEC);
|     ~~~~~^~~~~~~~~~~~~~~~~~~~
../../../../github/wayfire/wayfire.git/src/core/core.cpp:467:18: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
467 |             write(pipe_fd[WRITE_END], (void*)(&pid), sizeof(pid));
| …
=> Handle syscall failures in wf::compositor_core_impl_t::run

meson.build, metadata/input-device.xml, src/api/wayfire/config-backend.hpp, src/api/wayfire/debug.hpp, src/api/wayfire/plugin.hpp, src/core/core.cpp, src/core/plugin.cpp, src/core/seat/input-manager.cpp, src/core/seat/input-manager.hpp, src/core/seat/keyboard.cpp, src/core/seat/pointer.cpp, src/core/seat/pointing-device.cpp, src/core/seat/pointing-device.hpp, src/core/seat/seat-impl.hpp, src/core/seat/seat.cpp, src/main.cpp, src/meson.build
- Adds the ability to configure input devices that might have matching names
- Refactor so hotplugging a device only refreshes the configuration for that device, not all devices
- Add calibration option for touch devices
- Add a way to configure multiple keyboards and mice with different settings
=> Input device updates

src/core/plugin.cpp
=> config-backend: fallback to normal [input]

README.md, man/wayfire.1.in, src/default-config-backend.cpp
This PR adds support for vendoring the Wayfire configuration file.  In particular this means `${XDG_CONFIG_HOME}/wayfire/wayfire.ini` will take precedence over `${XDG_CONFIG_HOME}/wayfire.ini` while looking for a configuration file.
I opted to implement this change, since Wayfire already uses vendor-directories for plugin data in `${XDG_DATA_HOME}/wayfire/plugin`. Furthermore, I spent way too long trying to find out why my default configuration is not working.  I assume this change can reduce the maintenance burden, since people doing the same mistake will not open an issue or ask in IRC.
I copied it from `/usr/share/examples/wayfire/wayfire.ini` as packaged by my distro and therefore assumed wayfire uses the common vendor prefix pattern.  While researching my problem, I found several …
=> Allow Vendored Configuration File

src/core/plugin-loader.cpp, src/core/plugin-loader.hpp, src/main.cpp
This allows Wayfire to better detect when plugins have the wrong API/ABI.
For example with the old check, we load the full code of the plugin before checking its ABI.
But if the plugin includes symbols for example from header-only libraries (for example the way signals are),
then even fully loading the .so file is enough to corrupt the running process and cause a crash.
=> plugin-loader: check API/ABI version with RTLD_LAZY|RTLD_LOCAL

.github/workflows/ci.yaml, meson.build, meson_options.txt, plugins/animate/meson.build, plugins/blur/meson.build, plugins/cube/meson.build, plugins/decor/meson.build, plugins/grid/meson.build, plugins/ipc-rules/ipc-events.hpp, plugins/ipc-rules/ipc-rules-common.hpp, plugins/ipc-rules/meson.build, plugins/ipc/ipc-helpers.hpp, plugins/ipc/ipc-method-repository.hpp, plugins/ipc/ipc.hpp, plugins/ipc/meson.build, plugins/meson.build, plugins/pch/plugin_pch.hpp, plugins/protocols/meson.build, plugins/scale/meson.build, plugins/single_plugins/meson.build, plugins/tile/meson.build, plugins/tile/tile-ipc.hpp, plugins/vswitch/meson.build, plugins/window-rules/meson.build, plugins/wm-actions/meson.build, plugins/wobbly/meson.build, plugins/wobbly/wayfire/plugins/wobbly/wobbly-signal.hpp, src/api/wayfire/nonstd/wlroots.hpp, src/api/wayfire/per-output-plugin.hpp, src/meson.build
This PR adds support for PCH in plugins.
Mostly it is a workaround for https://github.com/mesonbuild/meson/issues/4350.
This does not work with all C++ compilers and is "use at own risk", therefore disabled by default. Can be enabled by passing `-Dcustom_pch=true` to meson. When disabled, it should not affect anything.
Speeds up compilation by at least 20% in local tests (48s vs 38s in plain build, 1m54s vs 1m40s in debugoptimized+asan).
=> Compilation time improvements (part 2)

metadata/input.xml, src/core/seat/pointing-device.cpp, src/core/seat/pointing-device.hpp
I don't like the tap-and-drag feature with touchpads because I have a lot of false positives when I use it. So, I suggest to add a setting to disable it.
By default, the option is still enabled.
=> Add an option to disable tap-and-drag gesture

metadata/xdg-activation.xml, plugins/protocols/xdg-activation.cpp
This adds three options to configure xdg-activation and allow more strict behavior. These include:
- reject requests without a view supplied (disabled by default)
- only allow activating with the last issued token (disabled by default)
- set the timeout used by wlroots (default: 30s, which is also used by wlroots)
Currently, wlroots already rejects token creation if the client supplied a wl_surface which is not focused. However, if there is no surface, creating a token always succeeds, basically allowing any app to focus itself (e.g. using `gtk_window_present()` which falls back to self-generated tokens with no surface if none is available in the environment). This can be a good thing e.g. when interacting with already running apps from the terminal, but can lead to unexpected focus …
=> xdg-activation: add options to make it more strict

meson.build, metadata/input.xml, src/core/seat/pointing-device.cpp, src/core/seat/pointing-device.hpp
This PR adds a setting to enable the new 3-finger/4-finger drag setting on libinput. See https://gitlab.freedesktop.org/libinput/libinput/-/merge_requests/1042 and https://who-t.blogspot.com/2025/02/libinput-and-3-finger-dragging.html for explanations and details about this feature (to summarize: this is an alternative to the tap-and-drag gesture).
This feature is currently on the main branch of libinput and will be available on the future 1.28 release. On Wayfire, the code to enable this feature is compiled only if the functions are implemented on the installed libinput version. To achieve that goal, I use a solution inspired from what is done on xf86-input-libinput project: in the meson file, I check if the function exists and then set (or not) a macro that is used to activate the code. …
=> Add an option to enable 3fg/4fg drag gesture

plugins/protocols/session-lock.cpp
Minimal changes to hide the screen contents in this case as well.
Simple test client: https://github.com/dkondor/simple_lock
=> session-lock: lock the screen even if the client provides no lock surface

plugins/window-rules/view-action-interface.cpp, plugins/window-rules/window-rules.cpp
Added logic to skip rule application for transient dialogs that are constrained to their parent window. 
The issue occurred because Wayfire tried to apply \`start_on_output\` rules to dialogs that could not leave their parent window. The fix ensures that such dialogs are ignored when applying output-changing rules.
fix #2619
=> Fix crash when applying window rules to constrained dialogs

src/view/layer-shell/layer-shell.cpp
Updating the geometry triggers a recomputation of surface visibility. Without it, once the layer-shell view goes offscreen (for ex. during autohide), it is computed as not visible on an output and does not receive `wl_surface.frame` events, leading to choppy animations.
Fixes https://github.com/WayfireWM/wf-shell/issues/189
Fixes https://github.com/WayfireWM/wf-shell/issues/276
Fixes https://github.com/WayfireWM/wf-shell/issues/287
=> layer-shell: notify scenegraph of geometry changes

.github/workflows/ci.yaml
This should no longer be necessary now that clang 19 is in the repos.
Undoes 1ceafa69edb00b8bb373793bb1090446cc5f5550
=> archlinux ci: stop using clang17 repository

.github/workflows/ci.yaml, plugins/single_plugins/resize.cpp
Some apps, notably a lot of Electron apps, set maximum size to INT_MAX, which will overflow the int32_t type when the margins of the server side decorations are added on top.
Use a larger integer type to calculate margins, then clamp as necessary, based on the actual type.
Fixes 099fea49800a5c2ed1a39f8c8513543e10362c18
=> resize: handle overflow due to margins

plugins/animate/squeezimize.hpp
This fixes a few different problems with squeezimize animation:
- Matches target width, even if surface width is smaller than target
- Fixes animation going out of damage bounds
- Fix disappearing surfaces when panel is on the bottom
=> animate: Improve squeezimize shader

plugins/ipc-rules/ipc-events.hpp, plugins/ipc-rules/ipc-rules-common.hpp, plugins/ipc-rules/ipc-utility-methods.hpp, src/api/wayfire/signal-definitions.hpp
Fixes #2419
See also https://github.com/WayfireWM/pywayfire/pull/24
=> ipc-rules: add events and methods to query keyboard layout

metadata/meson.build, plugins/meson.build, src/main.cpp, src/meson.build
`meson devenv -C build` allows entering a build folder with all environment variables prepared for easy execution without system-wide installation, automatically fixes things like the LD_LIBRARY_PATH.
Wayfire's plugin and backend loader systems rely on their own path discovery and configuration that devenv is unaware of, and so wayfire cannot launch out of the box in a devenv.
Adjust meson build files to augment WAYFIRE_PLUGIN_PATH and WAYFIRE_PLUGIN_XML_PATH so that plugins and XML files work by default. Add the WAYFIRE_DEFAULT_CONFIG_BACKEND environment variable to allow the devenv to provide a default for that as well, as it does not live together with the plugins.
With this, running wayfire straight from the repository is as simple as:
meson setup build
ninja -C build
meson devenv -C …
=> meson: Improve devenv support

plugins/ipc-rules/ipc-utility-methods.hpp
Currently, the IPC method `wayfire/get-config-option` just returns values of simple options. For all compound options, empty strings are returned. This PR extends the return values to include compound option entries.
=> Extend wayfire/get-config-option to return compound options

src/api/wayfire/scene-render.hpp
When looking into some rendering-related questions, I noticed that the docstring comment in one place does not match the parameters. This seems a straightforward change, so I suggest to update it.
=> scene-render: update a docstring comment to match function parameters

metadata/decoration.xml
close #2205 
Setting the title-bar or border height to 500 makes the view almost disappear, making wayfire unusable. The only fix is editing wayfire.ini from another desktop or compositor.
same for negative values, the view would disappear.
=> fix: decoration plugin title-bar/border height size issue

src/core/plugin.cpp
Even though linux supports redundant slashes: 
`WW 30-06-25 10:59:25.157 - [subprojects/wf-config/src/file.cpp:575] Failed to open XML directory /home/myuser/.local/share//wayfire/metadata`
=> Fix double slash in XDG metadata path construction

plugins/single_plugins/expo.cpp
The rest of the time we don't care.
Fixes #2589
=> expo: handle workspace grid changes when expo is active

metadata/workarounds.xml, src/default-config-backend.cpp
Fixes #2493 and potentially other long standing issues related to config reload.
An open question is whether we want to set the default to something like 50 or leave it to 0 to keep the old behavior. Thoughts?
=> feat: Add config reload delay option and refactor reload logic

plugins/animate/squeezimize.hpp
This adjusts the progress and sigmoid curve to improve squeezimize. Namely, this should make it so the window is not squeezed too much when first minimized.
Fixes #2720.
=> animate: Improve squeezimize animation

plugins/animate/squeezimize.hpp
Since I've started looking into the squeezimize shader, I though to try to create a horizontal version. This would be used for panels on the left / right edge of the screen. I belive the shared is working well now, but the heuristic for deciding whether to use the horizontal or vertical version could be improved: now, I just test which distance to the target box is larger, but this could unexpectedly choose the "wrong" animation, e.g. if the minimize location is close to a corner and the minimized view is on the other side of the screen. Potential alternatives:
- Add an option where the user can select
- Try to improve the heuristic, e.g. consider which screen edge the minimize position is closer to
- Actually look up the wl_surface set in the …
=> Squeezimize: horizontal version

src/render.cpp
Fixes the bokeh effect as reported on Matrix.
=> render: fix auxiliary buffer move constructor

src/view/xdg-shell.cpp
Don't bring a popup or subsurface to front as subsurfaces have their own order.
fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1943240. fixes #2566.
=> only bring toplevels to front

src/view/wlr-surface-node.cpp
Fixes #2749.
@stefonarch Can you test with thunderbird too? I was reproducing this issue with `firefox -P`, but I hope thunderbird's issue is the same.
=> surface-node: do not send frame events to unmapped surfaces

metadata/workarounds.xml, src/core/seat/seat.cpp
By default, if a grabbing layer-shell view is opened, Wayfire will keep the last focused toplevel activated. This makes it so that for example when you open bemenu, the focused view does change appearance. However, as seen in #1204, not everyone likes that. If you want to make sure that the currently focused toplevel loses the activated state when you open a keyboard-interactive layer-shell surface, set `workarounds/keep_last_toplevel_activated` to true.
Fixes #1204
=> workarounds: add keep_last_toplevel_activated option

src/core/core.cpp, src/core/window-manager.cpp
It could be that we request the view to be fullscreened on another
output, or on another workspace. The function might even be called to
readjust the geometry of a view which is already fullscreen.
=> window-manager: do not ignore fullscreen requests when already fullscreen

src/core/window-manager.cpp
This fixes dragging gtk4 apps with grid and/or wobbly disabled. The gtk4 toolkit sends a request for unfullscreen even though it is windowed, and this caused wayfire to set the geometry when dragging by titlebar, which made the window jump to an offset when grabbing the titlebar to move it. This was fixed before but broken by 60231d5d.
=> window-manager: Ignore unfullscreen requests if already windowed

plugins/common/move-drag-interface.cpp
We were sending a null output because the current output is not updated until after the snapoff signal is sent. Fix this by updating the output to the location of the grab when snapping off.
=> move-drag-interface: Fix move drag maximize snap off

src/view/xwayland/xwayland-toplevel-view.hpp
Not all diglogs want focus though they are focusable. In some strange cases, (e.g. WeChat, a famous chat application in China), the application's popup has both NORMAL and UTILITY type, we need to call wlr_xwayland_surface_offer_focus() for these views, in case they actually don't want focus.
=> xwayland: offer focus in global active cases

src/core/output-layout.cpp
The 'loaded mode' message is emitted during output initialization when enumerating available display modes. Since backend/drm/drm.c already handles that info, repeating this information at INFO level in Wayfire results in redundant output.
Fix #2787
=> output/layout: move 'loaded mode' message to debug logging

plugins/ipc-rules/ipc-utility-methods.hpp, src/core/output-layout.cpp
There is no straightforward or optimal method to list all configuration options via IPC.
This would help debug Wayfire issues by providing a full list of current options instead of relying on the config file, which scripts may have altered during the session.
Another use case: if a user has many options set and needs to verify whether the current config remains unchanged, for instance, after restarting an app that must decide whether to reapply settings, a complete option list simplifies comparison and skipping. I’m sure there are even more applications, personally, I find it quite useful.
```
In [3]: sock.list_config_options()["options"]["expo"]
Out[3]: 
{'background': {'value': '#01010180', 'default': '#1A1A1AFF'},
'duration': {'value': '300ms circle', 'default': '300ms circle'}, …
```
=> IPC method to list all config options
