WayfireWM/wayfire

plugins/animate/animate.cpp
plugins/single_plugins/grid.cpp
plugins/single_plugins/viewport-impl.cpp
plugins/single_plugins/vswitch.cpp
src/api/core.hpp
src/api/nonstd/observer_ptr.h
src/api/output.hpp
src/api/plugin.hpp
src/api/render-manager.hpp
src/api/view.hpp
src/api/workspace-manager.hpp
src/core.cpp
src/output/plugin-loader.cpp
src/output/plugin-loader.hpp
src/view/layer-shell.cpp
src/view/view.cpp
src/view/xdg-shell-v6.cpp
src/view/xdg-shell-v6.hpp
src/view/xdg-shell.cpp
src/view/xdg-shell.hpp
src/view/xwayland.cpp

Fixes #11
@soreau @AdrianVovk please test and tell me if there are any new bugs/crashes

use nonstd::observer_ptr for wayfire_view

---

plugins/cube/cube.cpp
plugins/single_plugins/expo.cpp
plugins/single_plugins/invert.cpp
plugins/single_plugins/meson.build
plugins/single_plugins/zoom.cpp
src/api/output.hpp
src/api/plugin.hpp
src/api/render-manager.hpp
src/api/view.hpp
src/core.cpp
src/input-manager.hpp
src/output/output.cpp
src/output/render-manager.cpp
src/view/priv-view.hpp
src/view/surface.cpp
src/view/view-util.cpp
src/view/view.cpp

Implements two plugins - zoom & invert, which use this functionality. Should be easy to add others as well.
Fixes #22 
Not all plugins proposed in the issue have been implemented, but the base is here.

Implement output postprocessing

---

plugins/single_plugins/fisheye.cpp
plugins/single_plugins/meson.build

This is a fisheye effect ported from compiz magnifier plugin fisheye fragment program.

Introduce fisheye plugin

---

plugins/single_plugins/fisheye.cpp

Apply output scale and rotation to mouse coordinates.

Transform mouse coordinates

---

plugins/single_plugins/alpha.cpp
plugins/single_plugins/meson.build

This basic alpha plugin allows changes a views transparency
by hovering the mouse cursor using binding <mod> + scroll.
It is also intended to facilitate a way to adjust the initial alpha
of a view when it is first mapped.

Add alpha plugin

---

plugins/single_plugins/grid.cpp
plugins/single_plugins/viewport-impl.cpp
src/api/core.hpp
src/api/object.hpp
src/api/output.hpp
src/api/signal-definitions.hpp
src/api/view.hpp
src/core/core.cpp
src/core/plugin.cpp
src/core/seat/keyboard.cpp
src/output/output.cpp
src/output/wayfire-shell.cpp
src/output/wayfire-shell.hpp
src/view/view.cpp

Fixes #46 
Now wayfire can be used with wlroots 0.1

Signals v2

---

plugins/single_plugins/command.cpp
src/core/core.cpp
src/core/seat/cursor.cpp
src/core/seat/cursor.hpp
src/core/seat/input-manager.cpp
src/core/seat/input-manager.hpp
src/core/seat/keyboard.cpp
src/core/seat/keyboard.hpp
src/core/seat/seat.cpp
src/core/seat/seat.hpp
src/core/seat/touch.cpp
src/main.cpp
src/output/output.cpp
wayfire.ini.default

This PR is stacked on top of #99 
Fixes #87 Fixes #63

Dynamic input options

---

src/api/debug.hpp
src/meson.build

Install API headers and pkgconfig file

---

src/core/seat/cursor.cpp
src/core/seat/cursor.hpp
src/core/seat/seat.cpp
src/core/seat/seat.hpp
wayfire.ini.default

(that screenshot of n9-settings is from weston, on wayfire it doesn't show current devices yet, and there are some other changes)

Add more input settings

---

plugins/animate/animate.cpp
plugins/cube/cubemap.cpp
plugins/cube/skydome.cpp
plugins/single_plugins/expo.cpp
plugins/single_plugins/viewport-impl.cpp
proto/wayfire-shell.xml
src/api/output.hpp
src/api/view.hpp
src/api/workspace-manager.hpp
src/core/core.cpp
src/core/img.cpp
src/core/seat/input-inhibit.cpp
src/core/seat/input-inhibit.hpp
src/core/seat/input-manager.cpp
src/core/seat/keyboard.cpp
src/output/output.cpp
src/output/wayfire-shell.cpp
src/view/layer-shell.cpp
src/view/view.cpp

@soreau needs testing, please check this + the `wayfire-shell-rework` branch in `wf-shell` to see if it works well enough.
@AdrianVovk If you are still developing your panel, you can update it to this version of wayfire-shell, I hope it doesn't break something for you. Tell me if you encounter any difficulties.

Wayfire shell rework

---

plugins/single_plugins/grid.cpp
plugins/single_plugins/viewport-impl.cpp

grid: listen for workarea changes and update tiled views

---

plugins/cube/cube.cpp
plugins/single_plugins/expo.cpp

Most notably Cube, Expo and perhaps others. (Will) fixes #54

Fix rendering for transformed and scaled outputs in plugins

---

src/output/plugin-loader.cpp

plugin-loader: Load a list of basic plugins in case of bad configuration

---

src/api/core.hpp
src/core/core.cpp
src/core/seat/cursor.cpp
src/core/seat/cursor.hpp
src/core/seat/input-manager.hpp

This goes after #129. This is separate from #129 as this adds new optional protocols.

Support new protocols

---

src/core/wm.cpp
src/core/wm.hpp
src/view/view.cpp
src/view/xdg-shell-v6.cpp
src/view/xdg-shell-v6.hpp
src/view/xdg-shell.cpp
src/view/xdg-shell.hpp

Stacked on top of #129 
Fixes #110

Fix 110 popup done

---

src/core/seat/input-manager.hpp
src/core/seat/seat.cpp

Changelog issue over there: https://github.com/swaywm/wlroots/issues/1569

Track wlroots 0.4

---

plugins/cube/cube.cpp
plugins/single_plugins/vswitch.cpp
plugins/wobbly/wobbly.c
plugins/wobbly/wobbly.cpp
plugins/wobbly/wobbly.h
src/api/util.hpp
wayfire.ini.default

Stacked on top of #181 
Fixes #103

Improve wobbly

---

plugins/single_plugins/viewport-impl.cpp
src/api/core.hpp
src/core/core.cpp
src/core/wm.cpp
src/core/wm.hpp
src/output/output.cpp
src/output/wayfire-shell.cpp
src/view/layer-shell.cpp
src/view/view.cpp

Fix 171 core layers focus

---

plugins/single_plugins/zoom.cpp

zoom: Don't sample from undefined area

---

src/core/output-layout.cpp

This fixes a couple problems that were causing black window with x11 backend.

Fixup x11 backend

---

meson.build
src/output/plugin-loader.cpp

RTTI is awesome https://stackoverflow.com/a/2352208
This fixes snap preview assertion failures and crashes.

Fix RTTI/dynamic_cast across plugins

---

plugins/blur/blur-base.cpp
plugins/blur/bokeh.cpp
plugins/blur/box.cpp
plugins/blur/gaussian.cpp
plugins/blur/kawase.cpp

kawase caught my eye when DTracing malloc..
---
also https://github.com/WayfireWM/wf-config/pull/11

blur: use cached config functions

---

plugins/single_plugins/grid.cpp

The default with no keybinding specified is to restore when the same keybinding
is used twice. Set 'restore' key in [grid] section to a keybinding to use a
dedicated keybinding instead. Fixes #240.

grid: Add way to restore with keybinding

---

src/api/core.hpp
src/core/core.cpp

https://github.com/swaywm/wlroots/commit/3dec88e4555ee5fd95ffd69133623816cb0c25c4
(I don't think we need a track-wlroots branch yet, since this change is backwards compatible)

Remove protocols removed by wlroots

---

proto/meson.build
src/api/core.hpp
src/api/util.hpp
src/core/core-impl.hpp
src/core/core.cpp
src/core/seat/cursor.cpp
src/core/seat/input-manager.hpp
src/util.cpp

Fixes #254 
As far as I know, this doesn't introduce any regressions. To anybody interested, check this, and report if it works (and also any regressions that have happened, although I don't expect any).

Pointer constraints

---

src/main.cpp

On FreeBSD running KMS+DRM session requires setuid bit but it'd needs to be dropped as applications may refuse to run. Taken from Sway.
```
$ env -u DISPLAY wayfire
2019-07-27 23:50:19 - [backend/session/direct-freebsd.c:163] Cannot open tty: Permission denied
2019-07-27 23:50:19 - [backend/session/session.c:96] Failed to load session backend
2019-07-27 23:50:19 - [backend/backend.c:321] Failed to start a DRM session
```

Drop root on startup like Sway

---

plugins/decor/deco-subsurface.cpp
plugins/single_plugins/grid.cpp
plugins/single_plugins/move.cpp
plugins/single_plugins/place.cpp
plugins/single_plugins/resize.cpp
plugins/single_plugins/window-rules.cpp
plugins/tile/tile.cpp
plugins/wobbly/wobbly.cpp
src/api/decorator.hpp
src/api/signal-definitions.hpp
src/api/view.hpp
src/core/output-layout.cpp
src/core/plugin.cpp
src/view/view-impl.cpp
src/view/view-impl.hpp
src/view/view.cpp
src/view/xdg-shell.cpp
src/view/xdg-shell.hpp
src/view/xwayland.cpp

core: rework tile, maximize and fullscreen APIs

---

src/core/output-layout.cpp
src/view/layer-shell.cpp

Stacked on top of #273 
Fixes a lot of bugs which can happen when running Wayfire with the Wayland or the X11 backend.

Nested compositor resize support

---

plugins/single_plugins/resize.cpp
src/core/seat/pointer.hpp

Add missing cmath include

---

plugins/single_plugins/expo.cpp
plugins/single_plugins/grid.cpp
plugins/single_plugins/move-snap-helper.hpp
plugins/single_plugins/move.cpp
plugins/single_plugins/resize.cpp
plugins/wobbly/wobbly-signal.hpp
plugins/wobbly/wobbly.c
plugins/wobbly/wobbly.cpp
plugins/wobbly/wobbly.h
src/api/geometry.hpp
src/api/nonstd/safe-list.hpp
src/core/core.cpp
src/core/seat/keyboard.cpp
src/output/workspace-impl.cpp
src/util.cpp
src/view/view.cpp

Wobbly rework

---

plugins/single_plugins/vswipe.cpp

@myfreeweb I'd appreciate if you can test this and tell me if it makes the experience better or worse. On my setup, I think smoothening the transitions makes it much better, but it'd make sense to gather some more opinions :)

vswipe: add smoothing of scrolling

---

src/view/layer-shell.cpp

This fixes building against wlroots as of 17242619.

layer-shell: Track wlroots changes

---

plugins/single_plugins/vswipe.cpp

Integrates changes posted in chat by @ammen99  that avoid damaging buffers on workspace switch (reducing stutter while using vswipe)

Avoid damage on vswipe (credit: ammen99)

---

src/output/plugin-loader.cpp

viewport_impl has been merged into core.

Remove viewport_impl from default_plugins list

---

src/output/render-manager.cpp

Fix broken background_color option

---

metadata/core.xml

Reference https://github.com/WayfireWM/wf-config/issues/19

core: Add plugins option

---

.gitmodules
README.md
meson.build
meson_options.txt

Supersedes #337
Note to package maintainers: ~~With this pull request, wf-config will be built together with Wayfire by default. You can use `-Duse_system_wlroots` and `-Duse_system_wfconfig` to configure the behavior.~~
wf-config and wlroots are now built by default **only** if they are not already installed, or if explicitly configured.

Submodules

---

src/api/wayfire/core.hpp
src/core/core-impl.hpp
src/core/core.cpp

This makes things like wayvnc pointer input work.

Add virtual pointer protocol

---

meson.build

build: compatible with wlroots-0.10.0

---

plugins/single_plugins/window-rules.cpp

This makes it possible to set the alpha on a view as part of the window rules.

Window rules: adds set alpha action.

---

.editorconfig
README.md
plugins/decor/deco-layout.hpp
plugins/wobbly/wobbly.cpp
src/api/wayfire/bindings.hpp
src/api/wayfire/singleton-plugin.hpp

make clang less annoyed + add [editorconfig](https://editorconfig.org/)

Warnings and stuff

---

metadata/alpha.xml
metadata/animate.xml
metadata/blur.xml
metadata/core.xml
metadata/cube.xml
metadata/decoration.xml
metadata/expo.xml
metadata/fast-switcher.xml
metadata/fisheye.xml
metadata/grid.xml
metadata/idle.xml
metadata/move.xml
metadata/oswitch.xml
metadata/simple-tile.xml
metadata/switcher.xml
metadata/vswipe.xml
metadata/vswitch.xml
metadata/wrot.xml
metadata/zoom.xml
wayfire.ini

This is based on #419 , but I am taking over the work since the previous PR still has review comments to address, and I'd like to see this in 0.4

Revamp option defaults

---

plugins/single_plugins/place.cpp

This mode will maximize all newly opened windows.
Not sure if the function can be simplified further. Looking for feedback. :)
Thanks!

plugins: add "maximize" mode to the place plugin

---

src/main.cpp

This requires adding a watch on the directory containing the config file.

Trigger config reload when config file is created

---

src/view/xwayland.cpp

This was causing xwayland views to jump workspaces when they configured
themselves. Instead of clamping to the output geometry, we clamp to
the desktop area, which is made up of all the workspaces.

xwayland: Clamp geometry to workspace area instead of output

---

plugins/single_plugins/idle.cpp

This makes screensaver per-output instead of single-instance. It fixes
several problems which aren't readily noticeable. For one, it makes it
so each instance is driven at the respective output refresh rate instead
of a single output driving all instances. This makes for a smoother
experience. Secondly, if an output was unplugged and another remained
active, the cube would get stuck grabbed until button press and then
would only restore back to untransformed when grabbing cube again. The
last bug this fixes is when an output was reconnected, the screensaver
was not running on it. This also hides mouse cursor when screensaver is
active.

idle: Overhaul screensaver

---

src/api/wayfire/view.hpp
src/view/view-impl.cpp
src/view/view-impl.hpp
src/view/view.cpp

Example.
wlr_box hint = { 0, 0, 0, 0};
view->set_minimize_hint(hint);

Add possibility to set_minimize_hint

---

meson.build
src/main.cpp

Adds -v --version.
Adds -h --help.
Adjust --damage-debug /  from -d to -D
Adjust --verbose -v to --debug -d
Also adds a new line for 'unrecognized parameter' / typo
Fixes #61

Adjust command line parameters

---

README.md

updated instructions for gentoo

wayfire now in gentoo main tree

---

metadata/wrot.xml
plugins/single_plugins/wrot.cpp

wrot: Add reset radius option

---

README.md

- Dependencies
- wf-shell
- Formatting

README: sync with wiki

---

.gitignore
metadata/decoration.xml
plugins/decor/decoration.cpp

Feature - Ignore window decoration for certain views matched by criteria

---

metadata/scale.xml
plugins/single_plugins/scale.cpp

Extra functionality to close a window by middle-clicking on it, similarly how it works in Compiz.

Scale close

---

src/core/seat/seat.cpp
src/core/seat/seat.hpp

drag-icons: store previous geometry and damage it

---

src/core/output-layout.cpp

output-layout: add more tests for output configuration

---

src/core/seat/keyboard.cpp

Fixes #590
Fixes #456
@damianatorrpm @Narrat does this help with your issues?

keyboard: check xkb options for errors

---

metadata/simple-tile.xml
plugins/tile/tile-plugin.cpp
plugins/tile/tree.cpp
plugins/tile/tree.hpp

This is a basic implementation, a few more options can be added later if needed.

tile: add support for outer and inner gaps

---

meson.build
proto/meson.build
src/meson.build

Currently `$prefix/wayfire/protocols'
Fixes #161

proto: install wayfire-shell-unstable to pkgdatadir

---

src/api/wayfire/signal-definitions.hpp
src/core/seat/input-manager.cpp
src/core/seat/input-manager.hpp
src/core/seat/pointer.cpp
src/core/seat/pointer.hpp
src/core/seat/tablet.cpp
src/core/seat/tablet.hpp
src/output/workspace-impl.cpp
src/view/view-impl.cpp

Fix focus on stack order changed

---

plugins/decor/deco-subsurface.cpp
plugins/decor/deco-subsurface.hpp
plugins/decor/decoration.cpp
src/api/wayfire/plugin.hpp
src/api/wayfire/view.hpp
src/view/view.cpp

Should fix #576 , @myfreeweb does it help?

Fix decoration destruction

---

src/core/matcher.cpp
src/output/workspace-impl.cpp

Misc fixes

---

metadata/input.xml
src/core/seat/keyboard.cpp
src/core/seat/pointing-device.cpp

Fixes #641 
Fixes #402 
Fixes #407

Pluralize xkb_option and xkb_rule and rename disable_while_typing

---

meson.build

Also wlroots 0.11.0 and latest wf-config
Fixes #596

update wayfire version to 0.5.0

---

meson.build

Adresses my comment in #596, depends on https://github.com/WayfireWM/wf-config/pull/28

Bump wf-config version.

---

src/view/xwayland.cpp

This fixes xwayland CSD minimize buttons for clients like steam and chrome.

xwayland: Handle minimize actions

---

src/core/output-layout.cpp

output-layout: set automatic positioning to false for client requests

---

src/core/seat/input-manager.cpp

input-manager: ignore minimized views when focusing

---

src/view/xwayland.cpp

The easiest way to do that is just destroy the old view and create a new one of the correct type.
Fixes #684 
@ovlx Can you test this and see if it works?

xwayland: add support for views that change OR status

---

plugins/blur/blur.cpp

blur: track padded areas in framebuffer-local coordinates

---

src/api/wayfire/core.hpp
src/api/wayfire/plugin.hpp
src/core/core-impl.hpp
src/core/core.cpp
src/core/output-layout.cpp
src/core/wm.cpp
src/core/wm.hpp
src/view/layer-shell.cpp

Fixes #219 and also a shutdown crash.

Fix nested shutdown

---

plugins/single_plugins/scale.cpp

A few simplifications I noticed, see individual commits for explanations

Scale fixes

---

src/output/output.cpp
src/view/view-impl.cpp
src/view/xdg-shell.cpp
src/view/xdg-shell.hpp

In preparation for https://github.com/swaywm/wlroots/pull/2391

Drop xdg shell v6

---

src/core/seat/seat.cpp

Otherwise, we can get a crash.

seat: do not assume drag will always have an icon

---

src/main.cpp

main: use wayland sockets from wayland-1 to wayland-32

---

src/core/output-layout.cpp

Handle views which have never been mapped better when unplugging an
output. Such views often occur in Xwayland applications for unknown reasons
(due to design of X probably). We shouldn't close these views because
they will cause the X clients to die. Instead, we can simply move them
to the new output.
Fixes #735

fix xwayland unplug crash

---

src/view/layer-shell.cpp

When we set the focused layer, we should consider views from all outputs, because the focused layer is global state.

layer-shell: always consider all views for focused layer

---

plugins/single_plugins/move.cpp
src/api/wayfire/output.hpp
src/api/wayfire/plugin.hpp
src/core/output-layout.cpp
src/output/output-impl.hpp
src/output/output.cpp

- output: new API for cancelling plugins and cancel on unplug
- move: take more care when force deactivating

API for cancelling plugins

---

src/view/xwayland.cpp

Xwayland position fix

---

src/output/output.cpp
src/view/xwayland.cpp

xwayland: ignore TRANSIENT_FOR for non-dialogue type windows

---

src/core/seat/cursor.cpp
src/main.cpp
src/view/view-impl.hpp
src/view/xwayland.cpp

xwayland: set seat and cursor whenever xwayland (re)starts

---

src/view/xwayland.cpp

Needs https://github.com/swaywm/wlroots/pull/2431

xwayland: listen to configure_notify for OR views.

---

src/view/view-impl.cpp
src/view/view.cpp

Implementation for https://github.com/swaywm/wlr-protocols/pull/52
Requires https://github.com/swaywm/wlroots/pull/2419 -- see my description there for more details

support for sending the parent with wlr_foreign_toplevel_handle

---

metadata/input.xml
src/core/seat/touch.cpp
src/core/seat/touch.hpp

touch: make gestures harder to misfire

---

metadata/vswitch.xml
plugins/scale/scale.cpp
plugins/vswitch/vswitch.cpp
plugins/vswitch/wayfire/plugins/vswitch.hpp

vswitch: add wraparound option for bindings

---

plugins/common/wayfire/plugins/common/cairo-util.hpp

Intended fix for #807 . 
Compiled and tested on intel gfx with no side effects.
Fixes #807

Swap channels for cairo surfaces sent to GL Textures

---

plugins/common/wayfire/plugins/common/move-snap-helper.hpp
plugins/single_plugins/move.cpp
plugins/single_plugins/resize.cpp

continuation on recreated branch from https://github.com/WayfireWM/wayfire/pull/633

Dont break fs 2

---

src/output/workspace-impl.cpp
src/view/view-impl.hpp

workspace-manager: move view layer data to view_impl

---

src/view/layer-shell.cpp

layer-shell: handle commits before mapping the surface

---

src/core/core-impl.hpp
src/core/core.cpp

core: reset last_active_view/toplevel on unmap()

---

metadata/blur.xml
plugins/blur/blur-base.cpp
plugins/blur/blur.hpp

This option controls the saturation of the blurred image.

blur: Add saturation option

---

meson.build

wayfire: bump version to 0.6.0

---

metadata/wm-actions.xml
plugins/wm-actions/wm-actions.cpp

wm-actions: Add bindings to minimize and toggle maximize

---

src/core/output-layout.cpp

hopefully this is acceptable .
Fixes #893

add custom modeline interlacing support

---

src/api/wayfire/signal-definitions.hpp
src/view/xdg-shell.cpp
src/view/xdg-shell.hpp

Emit signal on xdg.show_window_menu

---

src/output/render-manager.cpp

Fixes #874
Scanning out a view is possible only in a narrow set of cases:
- It must not interfere with plugins
- The view must have the correct size, buffer parameters, etc.

render-manager: attempt to directly scanout a view

---

plugins/single_plugins/place.cpp

Place plugin now uses signal_connection_t API

---

plugins/single_plugins/invert.cpp

fixes the issue introduced in #902

added missing sample call that was missing in #902

---

src/main.cpp

Core will already attach depth buffer so we don't need anything more.
This also is needed for Wayfire to support upcoming wlroots changes.

backend: do not attempt to modify the EGL created by wlroots

---

plugins/single_plugins/fast-switcher.cpp

this should fix #569 and makes Fast Switcher plugin more intuitive to use

Fast switcher uses focus order instead of stack order

---

plugins/cube/cube.cpp

When using cube with plugins like follow-focus output, grabbing the cube and
moving the pointer to another output resulted in the cube not reotating until
moving back to the grabbed output. This patch makes cube hold the pointer in
place while rotating, so it cannot move to any other output.

cube: Pin pointer so it does not move while rotating

---

plugins/scale/scale-title-filter.cpp
plugins/single_plugins/move.cpp
src/api/wayfire/plugin.hpp
src/api/wayfire/util.hpp
src/core/output-layout.cpp
src/core/seat/hotspot-manager.cpp
src/output/render-manager.cpp
src/output/wayfire-shell.cpp
src/util.cpp

~~Based on #924,~~
This PR adds support for repeatable timers in core.
This is used to implement key repeat in scale-title-filter.
Also, add the ability to match app-id in scale-title-filter as well.

scale filter add repeat

---

plugins/scale/scale.cpp

previously there was a lot of duplicated code because the main view and
children were handled separately. This is not really needed, so I
refactored it a bit and made animations for new child views in interactive
mode better.
Also added a few more comments so that the logic of the whole can be
followed easily.

scale: refactor layout_slots() logic

---

src/view/xwayland.cpp

skip deco for splash screens

---

wayfire.ini

And also fix subproject version.

wayfire.ini: fix example config output section

---

plugins/single_plugins/grid.cpp

fixes #929 
todo: need to find a way to set fullscreen for restore

grid: unset fullscreen for restore

---

plugins/animate/basic_animations.hpp
src/api/wayfire/core.hpp
src/api/wayfire/idle.hpp

- idle: use noncopyable_t
- core: fix -Wmismatched-tags on gesture_state_t
- animate: use named transformer for zoom

myfreebs patches

---

plugins/cube/cube.cpp

Add some special cases to cube to make it work in the cases vwidth=1,2
Fixes #583

fix cube 1 2 ws

---

src/api/wayfire/core.hpp
src/api/wayfire/nonstd/wlroots-full.hpp
src/api/wayfire/nonstd/wlroots.hpp
src/api/wayfire/plugin.hpp
src/core/core.cpp

Depends on https://github.com/swaywm/wlroots/pull/2487
Fixes #222

core: add xdg-foreign support

---

plugins/single_plugins/resize.cpp
src/view/xdg-shell.cpp
src/view/xwayland.cpp

- core: populate resize request edges when coming from a client
- resize: fix case where resize starts with no edges
Fixes #637

fix resize edges

---

src/core/seat/seat.hpp
src/output/render-manager.cpp
src/view/view-impl.hpp
src/view/xwayland.cpp

With this PR, a new kind of Xwayland views are added - drag and drop icons. They are special-cased just like regular DnD icons are.

xwayland: add special implementation for Xwayland DnD icons

---

proto/wlr-layer-shell-unstable-v1.xml
src/core/opengl.cpp

update wlr-layer-shell protocol

---

metadata/core.xml
src/api/wayfire/plugin.hpp
src/api/wayfire/signal-definitions.hpp
src/core/seat/cursor.cpp
src/core/seat/input-manager.hpp
src/core/seat/keyboard.cpp
src/core/seat/pointer.cpp
src/core/seat/pointer.hpp
src/core/seat/seat.hpp
src/core/seat/tablet.cpp
src/core/seat/tablet.hpp
src/core/seat/touch.cpp
src/core/seat/touch.hpp
src/core/wm.cpp
src/core/wm.hpp

- api: add handled field for input events
- focus: add option to not pass buttons to focused surface
- pointer: keep track of pressed buttons and send release on ungrab
Fixes #640
Fixes #1000
Fixes #997

disable event handling

---

src/view/view.cpp

I was experimenting and realized that reverse transform of coordinates in a view with 3D rotations does not work in interactive scale. Part of the reason is the FIXME that this PR aims to fix.
Note: this does not fix the original problem, since that is caused by the view_2D transformer always working with the untransformed WM geometry. I'll open a separate PR for that.

view: properly calculate bounding boxes for reverse transforms

---

src/view/view-3d.cpp

Alternative approach to #1051 
For 2D transformer, this allows accurate transform / untransform of coordinates even if it is not the first transform (like in the case of scale).
For 3D transformer, this fixes rendering artifacts such as on the image below (small region near the tooltip has tearing).

view-3d: 2D and 3D transformers should use tansformed WM geometry

---

plugins/single_plugins/resize.cpp

resize: fix calculation of resize edges

---

src/view/xwayland.cpp

Partial fix for #959
I could not find out why it doesn't show the menu when clicking on the first icon, but at least this fixes the positioning when it is fullscreen.

xwayland: fix handling of configure requests for fullscreen views

---

plugins/vswitch/wayfire/plugins/vswitch.hpp
src/output/output-impl.hpp
src/output/output.cpp
src/output/workspace-impl.cpp

This PR contains a few small fixes and heuristics to make the workspaces in Wayfire work better. I think it:
Fixes #861
Fixes #865
Fixes #930
Fixes #970
Let me know what you think about these changes (I see only the last two commits as a bit controversial but it makes things better IMO).
cc @pushqrdx @myfreeweb @travankor @ericonr

workspace fixes

---

plugins/decor/deco-layout.cpp
plugins/decor/deco-layout.hpp
plugins/decor/deco-subsurface.cpp

Implement #704, and prevent wobbly on simple click on tittle-bar

---

src/core/img.cpp

Signed-off-by: Aisha Tammy <floss@bsd.ac>

fix file pointer leak

---

src/output/render-manager.cpp

Should fix #1110
@jsmaniac can you try this + wlroots git?

render-manager: fix rendering of software cursors

---

src/core/seat/cursor.cpp
src/core/seat/cursor.hpp
src/output/render-manager.cpp

render-manager: make sure to bring EGL context for sw cursors

---

src/api/wayfire/core.hpp
src/api/wayfire/nonstd/wlroots-full.hpp
src/api/wayfire/nonstd/wlroots.hpp
src/core/core.cpp

https://github.com/swaywm/wlroots/pull/2460

Drop gtk-primary-selection which was dropped in wlroots

---

src/default-config-backend.cpp

This pull request fixes pull request #1107 and closes #1120.

Fix default-config-backend PR #1107

---

plugins/single_plugins/place.cpp

place: Fix potential division by zero

---

metadata/input.xml

Split input.xml into multiple sections

---

src/api/wayfire/view-transform.hpp
src/view/view.cpp

Might fix #1090, @soreau please test.

view: clamp damage to framebuffer and document the behavior

---

.github/workflows/ci.yaml

This builds the xwayland code paths that rely on WF_HAS_XWAYLAND being set.

CI: Add xwayland test

---

CONTRIBUTING.md

Added some instructions on how to format the code before committing.

CONTRIBUTING: Add code formatting instructions

---

metadata/zoom.xml
plugins/single_plugins/zoom.cpp

See the commit description for the warp fix.

zoom: Warp fix and Interpolation method option

---

src/core/seat/keyboard.cpp

This PR fixes #1166. Work done by @soreau

Fixing issue 1166

---

src/view/surface.cpp

Can be worked around via `-Duse_system_wlroots=disabled`.

Unbreak build with wlroots 0.14.0 (2021-06-03 snapshot)

---

meson.build

Bump wlroots and wf-config maximum required versions.

Bump dep versions

---

plugins/single_plugins/wrot.cpp

wrot: stop interactive rotate if the target view is unmapped

---

plugins/vswitch/wayfire/plugins/vswitch.hpp

vswitch: handle nullptr active view

---

plugins/animate/animate.cpp
plugins/animate/animate.hpp
plugins/animate/basic_animations.hpp
plugins/animate/fire/fire.cpp
plugins/animate/fire/fire.hpp
src/api/wayfire/plugin.hpp

Implement reverse animations

---

.github/workflows/ci.yaml

Drop dependency on external AUR helpers.

ci: attempt at fixing the archlinux build

---

src/view/xdg-shell.cpp

We needed some changes to track this wlroots change:
https://github.com/swaywm/wlroots/commit/0e342083440db978463dbf43795bfed8a5a11cd6
I also updated the wlroots submodule.

Track wlroots changes

---

src/output/workspace-impl.cpp

Promoted views make sense only for that layer. If a promoted view is moved to some of the other layers, it may become inaccessible because its promoted status is first cleared when it is moved back to the workspace layer.
We can simply ignore the promoted state as long as the view is not in the workspace layer. We also don't have to clear this state because it is unused. It will be recalculated when the view is brought back to the WORKSPACE layer.
Fixes #1076

workspace-manager: ignore promoted state for views not in WORKSPACE layer

---

.github/workflows/ci.yaml

CI: show diff for formatting code
Fixes #1252

CI: show uncrustify diff

---

src/api/wayfire/core.hpp
src/api/wayfire/nonstd/wlroots-full.hpp
src/core/opengl.cpp
src/core/output-layout.cpp
src/main.cpp
src/output/render-manager.cpp

#1351 and more (https://github.com/swaywm/sway/commit/5865af75cf8029cc703cda36b68daafcb658c97b)
hopefully the comment is correct :D

Track wlroots again

---

.github/workflows/ci.yaml

Remove the old workaround now that seatd is officially packaged.

CI: use seatd package

---

meson.build
src/api/wayfire/nonstd/wlroots-full.hpp

Fix warnings when compiling with wlroots-git

bump wlroots version to wlroots-git

---

src/core/core.cpp

This was missing in the last PR.

core: create wlr_subcompositor

---

plugins/wobbly/wobbly.h

Update wobbly license

---

src/api/wayfire/signal-definitions.hpp
src/core/seat/cursor.cpp
src/core/seat/cursor.hpp
src/core/seat/pointer.cpp
src/core/seat/pointer.hpp

Catching up to wlroots: https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/d069a783bcafe65c240f2369b68f5e8d45d0b9a2 (we depend on a newer revision I'm pretty sure)

seat: add touchpad hold gesture support

---

src/output/workspace-impl.cpp

Offset by current workspace to get the correct result.

workspace-impl: Fix get_view_main_workspace()

---

plugins/ipc/stipc.cpp

stipc: add ipc call to configure view layout

---

plugins/ipc/ipc.cpp
plugins/ipc/stipc.cpp

ipc: remove debug output which is not useful anymore

---

src/core/seat/cursor.cpp
src/core/seat/touch.cpp
src/core/seat/touch.hpp

touch: handle frame and cancel events

---

src/core/img.cpp

Patch by @soreau to fix the inverted image while taking view snapshot

BugFix: fix inverted image when writing to file

---

src/output/output.cpp
src/view/view-node.cpp

Fixes #1633
@bklaase Can you confirm?

view: focus only iff the view is visible on the current workspace

---

plugins/decor/deco-layout.cpp
plugins/tile/tree-controller.cpp
src/core/core.cpp
src/view/view.cpp
uncrustify.ini

Let's use a longer column limit, displays these days are bigger.

uncrustify: increase column limit to 110 characters

---

plugins/decor/decoration.cpp
src/api/wayfire/plugin.hpp

@ammen99 I believe you wanted to remove this bit..

Remove unused 'wf::plugin_activation_data_t' from deco

---

plugins/wm-actions/wm-actions.cpp
src/core/scene.cpp
src/output/output.cpp

This was the patch @soreau cooked up to fix the issue with `always_on_top`. It works :tm:, but has a few issues - See the last two comments in #1637

Fix for #1637

---

src/api/wayfire/signal-definitions.hpp
src/output/output.cpp

This signal might be removed in the future.

Add pre_focus_view_signal for FSP

---

metadata/switcher.xml
plugins/single_plugins/switcher.cpp

hI, i added ability to change rotation of the thumbnail images 
<details>
<summary>Thumbnail rotated by 0 degrees</summary>
</details>
also added ability to switch views from the current active window

Switcher: Rotate and switch views from the active one

---

metadata/move.xml
metadata/simple-tile.xml
plugins/common/wayfire/plugins/common/preview-indication.hpp
plugins/single_plugins/move.cpp
plugins/tile/tree-controller.cpp

Implements some features requested in #1427

configurable `preview_indicator_t`

---

plugins/single_plugins/ipc-rules.cpp

ipc-rules: add command to query focused view

---

README.md

We have a new nixos module for wayfire:
https://github.com/NixOS/nixpkgs/pull/236041
https://github.com/NixOS/nixpkgs/pull/245916
nixpkgs-wayland droped wayfire
https://github.com/nix-community/nixpkgs-wayland/issues/395

readme: update how to use in nixos

---

.editorconfig
plugins/decor/deco-subsurface.cpp
src/view/view-impl.cpp
src/view/view-impl.hpp
src/view/view.cpp
src/view/xdg-shell.cpp
src/view/xdg-shell/xdg-toplevel-view.cpp
src/view/xdg-shell/xdg-toplevel-view.hpp
src/view/xdg-shell/xdg-toplevel.cpp
src/view/xwayland.cpp
src/view/xwayland/xwayland-toplevel-view.hpp
src/view/xwayland/xwayland-toplevel.cpp
src/view/xwayland/xwayland-unmanaged-view.hpp
src/view/xwayland/xwayland-view-base.hpp

This PR aims to fix a few problems still remaining with unmapping/remapping views.
Planned issues to fix:

Fix unmapping-related issues

---

ipc-scripts/wayfire_socket.py
plugins/single_plugins/ipc-rules.cpp

* Add window-rules/focus-view method to window-rules plugins
* Add focus method to wayfire_socket.py

ipc-rules: add focus method for ipc

---

plugins/grid/grid.cpp
plugins/ipc/stipc.cpp
plugins/scale/meson.build
plugins/scale/scale-title-filter.cpp
plugins/scale/scale.cpp
plugins/vswitch/vswitch.cpp
plugins/vswitch/wayfire/plugins/vswitch.hpp

Fix a few plugin issues

---

src/view/view-impl.cpp
src/view/view-impl.hpp

core: Backport 'Implement wlr_foregin_toplevel_handle's fullscreen' fix

---

plugins/common/wayfire/plugins/common/preview-indication.hpp
src/view/layer-shell/layer-shell.cpp

Fix damage issues

---

plugins/common/wayfire/plugins/common/move-drag-interface.hpp
plugins/decor/decoration.cpp
plugins/ipc/stipc.cpp
plugins/scale/scale.cpp
plugins/single_plugins/expo.cpp
plugins/single_plugins/move.cpp
plugins/wobbly/wobbly.cpp
src/output/output.cpp
src/view/xwayland/xwayland-toplevel-view.hpp
src/view/xwayland/xwayland-unmanaged-view.hpp

- stipc: add get_xwayland_display
- xwayland: rewrite mapping functionality
- xwayland-unmanaged-view: improve tracking of position
@EoceneMiacid @soreau Can you test again with steam (and any other Xwayland clients which are important for you)?
Fixes #1859 
Fixes #1881 
Fixes #1862

xwayland + other fixes

---

plugins/wobbly/wobbly.cpp

wobbly: Fix wobbly after second grab while wobbling

---

meson.build

Fix issues with meson.build

---

metadata/workarounds.xml
plugins/ipc/stipc.cpp
plugins/tile/tile-plugin.cpp
plugins/tile/tree.cpp
src/core/core.cpp
src/core/seat/seat.cpp
src/debug.cpp
src/output/output.cpp
src/view/layer-shell/layer-shell.cpp
src/view/subsurface.cpp
src/view/subsurface.hpp
src/view/surface-impl.hpp
src/view/surface.cpp
src/view/xdg-shell.cpp
src/view/xdg-shell/xdg-toplevel-view.cpp
src/view/xdg-shell/xdg-toplevel-view.hpp
src/view/xdg-shell/xdg-toplevel.cpp
src/view/xwayland/xwayland-toplevel-view.hpp
src/view/xwayland/xwayland-toplevel.cpp

Another PR with a few planned bug fixes:

Fix a few bugs

---

meson.build

* correct version from 0.16 which is the version of wlroots to 0.8

Fix wf-config version when using wf-config from system

---

src/core/output-layout.cpp

output-layout: emit output-layout-configuration-changed when mode changes

---

plugins/single_plugins/wsets.cpp
plugins/vswitch/wayfire/plugins/vswitch.hpp
src/api/wayfire/unstable/translation-node.hpp
src/core/seat/seat.cpp
src/view/translation-node.cpp

Fixes #1920
Fixes #1915
Fixes #1916

Fix a few regressions

---

man/meson.build

meson: fix duplicate installation of manpage

---

src/view/layer-shell/layer-shell.cpp

Small fix to setting focus of on_demand layer shell surfaces

---

plugins/wm-actions/wm-actions.cpp

wm-actions: fix toggle always on top with no focused views

---

plugins/ipc/stipc.cpp
plugins/single_plugins/ipc-rules.cpp

This also lists the views in z-order.
Fixes #2009

ipc plugins: Move list-views from stipc to ipc-rules

---

src/core/window-manager.cpp
src/core/wm.cpp

fix handling of focus of views with null keyboard focus view

---

src/api/wayfire/nonstd/wlroots-full.hpp
src/core/core.cpp

Advertise support for single-pixel-buffer-v1

---

src/core/idle.cpp

idle-inhibit: Fix inversed condition for working client inhibit

---

plugins/single_plugins/idle.cpp

idle: Fix stuck black screen after timeout with cube disabled

---

src/output/workspace-impl.cpp

soreau's fix to prevent clients from resizing proportional to output size

Don't resize clients when output is resized

---

plugins/common/wayfire/plugins/common/move-drag-interface.hpp
plugins/scale/scale.cpp
plugins/single_plugins/expo.cpp
plugins/single_plugins/move.cpp
src/core/seat/pointer.cpp
src/core/seat/pointer.hpp

pointer: mark updates caused by geometry change as real updates

---

plugins/single_plugins/ipc-rules.cpp

ipc: add close-view

---

src/core/opengl.cpp

- opengl: report linking errors from program compilation as well
- opengl: print an error if trying to set uniforms which don't exist

gl wrapper improvements

---

plugins/ipc/stipc.cpp
plugins/scale/scale.cpp
plugins/tile/tile-plugin.cpp
plugins/vswitch/vswitch.cpp
plugins/vswitch/wayfire/plugins/vswitch.hpp
src/api/wayfire/output-layout.hpp
src/core/core-impl.hpp
src/core/core.cpp
src/core/opengl.cpp
src/core/output-layout.cpp
src/core/plugin-loader.cpp
src/core/plugin-loader.hpp
src/core/seat/tablet.cpp
src/main.cpp
src/output/workspace-impl.cpp
src/util.cpp
src/view/xdg-shell/xdg-toplevel-view.cpp

Fixes #2154
Fixes #2201 
Fixes #729

core: fix shutdown sequence

---

metadata/scale.xml
plugins/scale/scale.cpp

There is an option to set space between views which is useful to set in the edges too
the default space for edges look like this:

Set space between the edges

---

ipc-scripts/input.py

add ipc-scripts/input.py

---

meson.build
subprojects/json.wrap

This is a regression introduced in #2226

meson.build: fix autodetection of xwayland support

---

plugins/tile/tile-dragging.hpp

simple-tile: fix swapping of nodes with the same parent

---

.github/workflows/ci.yaml
plugins/blur/blur.cpp
plugins/common/wayfire/plugins/common/move-drag-interface.hpp
plugins/cube/cube.cpp
plugins/wobbly/wobbly.cpp
src/api/wayfire/plugin.hpp
src/api/wayfire/render-manager.hpp
src/api/wayfire/view-transform.hpp
src/output/render-manager.cpp
src/view/view-3d.cpp

This PR aims to add more optimizations to Wayfire transformers and plugins, mostly aimed at reducing their VRAM usage and also some generic optimizations.
Fixes #2184

transformer optimizations

---

plugins/protocols/input-method-v1.cpp

imv1: fix null text_input crash by clearing it later

---

src/view/xdg-shell/xdg-toplevel-view.cpp

xdg-shell: unset priv->wsurface on destroy

---

meson.build
plugins/common/wayfire/plugins/common/input-grab.hpp
plugins/common/wayfire/plugins/common/move-drag-interface.hpp
plugins/grid/grid.cpp
plugins/scale/scale.cpp
plugins/tile/tile-ipc.hpp
plugins/tile/tile-plugin.cpp
plugins/tile/tree-controller.cpp
plugins/tile/tree-controller.hpp
plugins/vswitch/vswitch.cpp
src/core/seat/pointer.cpp
src/core/seat/pointer.hpp
src/view/xwayland/xwayland-toplevel-view.hpp

fix killown crashes

---

plugins/common/wayfire/plugins/common/move-drag-interface.hpp
plugins/tile/tile-plugin.cpp
plugins/wobbly/wobbly.c
src/api/wayfire/render-manager.hpp
src/api/wayfire/view-transform.hpp
src/core/txn/transaction-manager-impl.hpp
src/output/output-impl.hpp
src/output/output.cpp
src/output/render-manager.cpp
src/view/wlr-surface-node.cpp
src/view/xdg-shell/xdg-toplevel-view.cpp
src/view/xwayland/xwayland-toplevel-view.hpp

even more fixes

---

metadata/core.xml
src/view/view-impl.cpp
src/view/view-impl.hpp
src/view/xwayland.cpp

Add lazy start config option for XWayland which is built into wlroots, similar to sway.

xwayland: add lazy start config option

---

src/api/wayfire/object.hpp

Bug: https://bugs.gentoo.org/938288

Add missing include for gcc-15

---

plugins/common/wayfire/plugins/common/util.hpp

util.hpp: Fix clicking on open dialogs in scale and expo

---

plugins/grid/grid.cpp

grid: restore unfulscreened views to their correct position

---

plugins/animate/squeezimize.hpp

Fixes #2533
Test: https://github.com/ammen99/wayfire-tests/commit/30e73a39c09b30b232eed6c5465d538a0d98814a

squeezimize: remove transformer at the appropriate time

---

src/view/xdg-shell.cpp

Fix originally by @ammen99 https://github.com/WayfireWM/wayfire/issues/2445#issuecomment-2308395997
Fixes #2445 (this just happened to me again :))

xdg-shell: fix potential crash with inert popups

---

plugins/ipc-rules/ipc-rules-common.hpp

ipc-rules: fix wset-index garbage values

---

plugins/ipc-rules/ipc-events.hpp

ipc-rules: Fix view-fullscreen event

---

.gitignore
metadata/core.xml
src/view/xwayland.cpp

xwayland: add core option for XWayland startup script

---

src/core/seat/cursor.cpp
src/core/seat/cursor.hpp

Optimize setting cursors

---

metadata/resize.xml
plugins/single_plugins/resize.cpp

Add min-width and min-height options to the resize plugin.

---

src/view/xdg-shell.cpp

by calling unconstrain on initial commit.
Fixes #2189.

avoid scheduling a configure for an uninitialized xdg_surface

---

plugins/cube/cube.cpp
plugins/single_plugins/fisheye.cpp
plugins/single_plugins/invert.cpp
plugins/single_plugins/switcher.cpp
plugins/wobbly/wobbly.cpp
src/api/wayfire/core.hpp
src/api/wayfire/plugin.hpp
src/core/core.cpp

standardized warnings when GLES2 plugins attempt to run on unsupported renderers

---

plugins/single_plugins/zoom.cpp

zoom: add safety checks for texture source box

---

src/core/core.cpp

core: handle suggested output for virtual-pointer

---

src/api/wayfire/plugin.hpp
src/api/wayfire/window-manager.hpp
src/core/window-manager.cpp
src/view/xwayland/xwayland-toplevel-view.hpp

Fixes #2585
@killown @AgostinoA please test
Ref https://github.com/ammen99/wayfire-tests/commit/af28073d2143db90d371dcf89807a86629422488

window-manager: add function to directly store windowed geometry

---

src/core/seat/seat.cpp
src/core/seat/tablet.hpp

Fixes https://github.com/WayfireWM/wayfire/issues/2776

Fix drawing tablets not mapping to output

---

plugins/common/move-drag-interface.cpp
src/api/wayfire/plugin.hpp
src/api/wayfire/scene-operations.hpp
src/api/wayfire/scene-render.hpp
src/api/wayfire/scene.hpp
src/core/scene.cpp
src/output/render-manager.cpp

scene: add helper for managing render instances

---

plugins/window-rules/view-action-interface.cpp
src/core/output-layout.cpp

remove unnecessary log from _set_alpha

---

src/core/output-layout.cpp
src/view/xwayland/xwayland-unmanaged-view.hpp

LOG: change new unmanaged xwayland surface to LOGC

---

src/core/output-layout.cpp

output-layout: zero-initialize output mode

---

locale/meson.build
meson.build
meson_options.txt

This fix was suggested by @soreau and I am applying it here as well

fix build of multiple locales
